
package com.cnk.travelogix.custom.zifws.account.clear;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountClearing", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/C:/CNK-Documents/SAP-Backend-Integration/WSDL/ECC/zifws_account_clear_1.wsdl")
public class AccountClearing
    extends Service
{

    private final static URL ACCOUNTCLEARING_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTCLEARING_EXCEPTION;
    private final static QName ACCOUNTCLEARING_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "AccountClearing");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/CNK-Documents/SAP-Backend-Integration/WSDL/ECC/zifws_account_clear_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTCLEARING_WSDL_LOCATION = url;
        ACCOUNTCLEARING_EXCEPTION = e;
    }

    public AccountClearing() {
        super(__getWsdlLocation(), ACCOUNTCLEARING_QNAME);
    }

    public AccountClearing(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTCLEARING_QNAME, features);
    }

    public AccountClearing(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTCLEARING_QNAME);
    }

    public AccountClearing(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTCLEARING_QNAME, features);
    }

    public AccountClearing(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountClearing(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZIFWSACCOUNTCLEAR
     */
    @WebEndpoint(name = "ZIFWS_Account_Clear")
    public ZIFWSACCOUNTCLEAR getZIFWSAccountClear() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZIFWS_Account_Clear"), ZIFWSACCOUNTCLEAR.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZIFWSACCOUNTCLEAR
     */
    @WebEndpoint(name = "ZIFWS_Account_Clear")
    public ZIFWSACCOUNTCLEAR getZIFWSAccountClear(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZIFWS_Account_Clear"), ZIFWSACCOUNTCLEAR.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTCLEARING_EXCEPTION!= null) {
            throw ACCOUNTCLEARING_EXCEPTION;
        }
        return ACCOUNTCLEARING_WSDL_LOCATION;
    }

}
