
package com.cnk.travelogix.custom.zif.erp.ws.custmastercreate.b2b;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZIF_ERP_WS_CUSTOMER_CREATE_B2B", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/C:/CNK-Documents/SAP-Backend-Integration/WSDL/CRM/hybriscrm_zif_erp_ws_customer_create_b2b.wsdl")
public class ZIFERPWSCUSTOMERCREATEB2B_Service
    extends Service
{

    private final static URL ZIFERPWSCUSTOMERCREATEB2B_WSDL_LOCATION;
    private final static WebServiceException ZIFERPWSCUSTOMERCREATEB2B_EXCEPTION;
    private final static QName ZIFERPWSCUSTOMERCREATEB2B_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "ZIF_ERP_WS_CUSTOMER_CREATE_B2B");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/CNK-Documents/SAP-Backend-Integration/WSDL/CRM/hybriscrm_zif_erp_ws_customer_create_b2b.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZIFERPWSCUSTOMERCREATEB2B_WSDL_LOCATION = url;
        ZIFERPWSCUSTOMERCREATEB2B_EXCEPTION = e;
    }

    public ZIFERPWSCUSTOMERCREATEB2B_Service() {
        super(__getWsdlLocation(), ZIFERPWSCUSTOMERCREATEB2B_QNAME);
    }

    public ZIFERPWSCUSTOMERCREATEB2B_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZIFERPWSCUSTOMERCREATEB2B_QNAME, features);
    }

    public ZIFERPWSCUSTOMERCREATEB2B_Service(URL wsdlLocation) {
        super(wsdlLocation, ZIFERPWSCUSTOMERCREATEB2B_QNAME);
    }

    public ZIFERPWSCUSTOMERCREATEB2B_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZIFERPWSCUSTOMERCREATEB2B_QNAME, features);
    }

    public ZIFERPWSCUSTOMERCREATEB2B_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZIFERPWSCUSTOMERCREATEB2B_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZIFERPWSCUSTOMERCREATEB2B
     */
    @WebEndpoint(name = "ZIF_ERP_WS_CUSTOMER_CREATE_B2B")
    public ZIFERPWSCUSTOMERCREATEB2B getZIFERPWSCUSTOMERCREATEB2B() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZIF_ERP_WS_CUSTOMER_CREATE_B2B"), ZIFERPWSCUSTOMERCREATEB2B.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZIFERPWSCUSTOMERCREATEB2B
     */
    @WebEndpoint(name = "ZIF_ERP_WS_CUSTOMER_CREATE_B2B")
    public ZIFERPWSCUSTOMERCREATEB2B getZIFERPWSCUSTOMERCREATEB2B(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZIF_ERP_WS_CUSTOMER_CREATE_B2B"), ZIFERPWSCUSTOMERCREATEB2B.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZIFERPWSCUSTOMERCREATEB2B_EXCEPTION!= null) {
            throw ZIFERPWSCUSTOMERCREATEB2B_EXCEPTION;
        }
        return ZIFERPWSCUSTOMERCREATEB2B_WSDL_LOCATION;
    }

}
