

package supplierratedefinitionsaccommodation;

import java.util.*;
import java.io.Serializable;
import de.hybris.platform.util.*;
import de.hybris.platform.core.*;
import de.hybris.platform.jalo.JaloBusinessException;
import de.hybris.platform.jalo.type.*;
import de.hybris.platform.persistence.type.*;
import de.hybris.platform.persistence.enumeration.*;
import de.hybris.platform.persistence.property.PersistenceManager;
import de.hybris.platform.persistence.*;

/**
 * Generated by hybris Platform.
 */
@SuppressWarnings({"cast","unused","boxing","null", "PMD"})
public class GeneratedTypeInitializer extends AbstractTypeInitializer
{
	/**
	 * Generated by hybris Platform.
	 */
	public GeneratedTypeInitializer( ManagerEJB manager, Map params )
	{
		super( manager, params );
	}


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected void performRemoveObjects( ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// no-op by now
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateTypes
	
	
		createItemType(
			"AccommodationSupplierRate",
			"AbstractSupplierRate",
			com.cnk.travelogix.supplier.rates.jalo.supplierrates.accommodation.AccommodationSupplierRate.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"AccommodationRateDefinition",
			"AbstractRateDefinition",
			com.cnk.travelogix.supplier.rates.jalo.supplierrates.accommodation.AccommodationRateDefinition.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"AccoRateDetailDefinition",
			"GenericItem",
			com.cnk.travelogix.supplier.rates.supplierrate.jalo.accommodation.AccoRateDetailDefinition.class,
			"de.hybris.platform.persistence.supplierratedefinitionsaccommodation_AccoRateDetailDefinition",
			false,
			null,
			false
		);
	
		createItemType(
			"RoomTypeRate",
			"GenericItem",
			com.cnk.travelogix.supplier.rates.supplierrate.jalo.common.RoomTypeRate.class,
			"de.hybris.platform.persistence.supplierratedefinitionsaccommodation_RoomTypeRate",
			false,
			null,
			false
		);
	
		createItemType(
			"AccoSurchargeSuppDetail",
			"AbstractSurchargeSuppDetail",
			com.cnk.travelogix.supplier.rates.supplierrate.jalo.accommodation.AccoSurchargeSuppDetail.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"SupplierRoomOffer",
			"GenericItem",
			com.cnk.travelogix.supplier.rates.supplierrate.jalo.common.SupplierRoomOffer.class,
			"de.hybris.platform.persistence.supplierratedefinitionsaccommodation_SupplierRoomOffer",
			false,
			null,
			false
		);
	
		createItemType(
			"CommonAncillaryRateDetail",
			"AbstractAncillaryRateDetail",
			com.cnk.travelogix.supplier.rates.supplierrate.jalo.ancillary.CommonAncillaryRateDetail.class,
			"de.hybris.platform.persistence.supplierratedefinitionsaccommodation_CommonAncillaryRateDetail",
			false,
			null,
			false
		);
	
		createRelationType(
			"AccoRateDef2AccoRateDetailDefRel",
			null,
			true
		);
	
		createRelationType(
			"AccoRateDetailDefinition2RoomTypeRateRel",
			null,
			true
		);
	
		createRelationType(
			"CommonRateAdvDefinition2SupplierRoomOfferRel",
			null,
			true
		);
	
		createRelationType(
			"AccoRateDef2AccoDynamicPolicyRel",
			"de.hybris.platform.persistence.link.supplierratedefinitionsaccommodation_AccoRateDef2AccoDynamicPolicyRel",
			false
		);
	
		createRelationType(
			"AccoRateDetailDefinition2AbstractTravelogixSupplierOfferRel",
			"de.hybris.platform.persistence.link.supplierratedefinitionsaccommodation_AccoRateDetailDefinition2AbstractTravelogixSupplierOfferRel",
			false
		);
	
		createRelationType(
			"AccoRateDetailDefinition2ChildAgeRateDetailRel",
			null,
			true
		);
	
		createEnumerationType(
			"AccoSurchargeSubType",
			null
		);
	
		createEnumerationType(
			"ChildBedType",
			null
		);
	
		createEnumerationType(
			"RateFor",
			null
		);
	
		createEnumerationType(
			"MealPlanType",
			null
		);
	
		createEnumerationType(
			"DurationType",
			null
		);
	
		createEnumerationType(
			"VehicleType",
			null
		);
	
		createCollectionType(
			"RoomCategorySet",
			"RoomCategory",
			CollectionType.SET
		);
	
		createCollectionType(
			"RoomTypeSet",
			"RoomType",
			CollectionType.SET
		);
	
		createCollectionType(
			"MealPlanTypeSet",
			"MealPlanType",
			CollectionType.SET
		);
	
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performModifyTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performModifyTypes
	

	
	
				single_createattr_AccommodationRateDefinition_priceApplicability();
			
				single_createattr_AccommodationRateDefinition_noOfRooms();
			
				single_createattr_AccommodationRateDefinition_comparator();
			
				single_createattr_AccommodationRateDefinition_surchargeSupplement();
			
				single_createattr_AccoRateDetailDefinition_minNights();
			
				single_createattr_AccoRateDetailDefinition_dayOfWeek();
			
				single_createattr_AccoRateDetailDefinition_rateDefinedFor();
			
				single_createattr_AccoRateDetailDefinition_roomCategory();
			
				single_createattr_AccoRateDetailDefinition_proRata();
			
				single_createattr_AccoRateDetailDefinition_stayDuration();
			
				single_createattr_AccoRateDetailDefinition_rateFor();
			
				single_createattr_AccoRateDetailDefinition_mealPlan();
			
				single_createattr_AccoRateDetailDefinition_checkInTime();
			
				single_createattr_AccoRateDetailDefinition_checkOutTime();
			
				single_createattr_AccoRateDetailDefinition_commissionExcluded();
			
				single_createattr_AccoRateDetailDefinition_childAge();
			
				single_createattr_AccoRateDetailDefinition_noOfChild();
			
				single_createattr_AccoRateDetailDefinition_noOfAdults();
			
				single_createattr_AccoRateDetailDefinition_adultAge();
			
				single_createattr_AccoRateDetailDefinition_rate();
			
				single_createattr_AccoRateDetailDefinition_minPaxOccupancy();
			
				single_createattr_AccoRateDetailDefinition_maxPaxOccupancy();
			
				single_createattr_AccoRateDetailDefinition_payOnArrival();
			
				single_createattr_AccoRateDetailDefinition_commonRateAdvDefinition();
			
				single_createattr_RoomTypeRate_rate();
			
				single_createattr_RoomTypeRate_roomType();
			
				single_createattr_RoomTypeRate_payOnArrival();
			
				single_createattr_AccoSurchargeSuppDetail_subType();
			
				single_createattr_AccoSurchargeSuppDetail_roomCategories();
			
				single_createattr_AccoSurchargeSuppDetail_roomTypes();
			
				single_createattr_AccoSurchargeSuppDetail_mealPlan();
			
				single_createattr_AccoSurchargeSuppDetail_stdCommissionValue();
			
				single_createattr_AccoSurchargeSuppDetail_stdCommissionType();
			
				single_createattr_AccoSurchargeSuppDetail_amount();
			
				single_createattr_SupplierRoomOffer_roomCategory();
			
				single_createattr_SupplierRoomOffer_roomType();
			
				single_createattr_SupplierRoomOffer_maxNoOfRooms();
			
				single_createattr_CommonAncillaryRateDetail_startTime();
			
				single_createattr_CommonAncillaryRateDetail_durationType();
			
				single_createattr_CommonAncillaryRateDetail_durationValue();
			
				single_createattr_CommonAncillaryRateDetail_seatingType();
			
				single_createattr_CommonAncillaryRateDetail_costApplicability();
			
				single_createattr_CommonAncillaryRateDetail_paxType();
			
				single_createattr_CommonAncillaryRateDetail_childAge();
			
				single_createattr_CommonAncillaryRateDetail_vehicleType();
			
				single_createattr_CommonAncillaryRateDetail_portName();
			
		createRelationAttributes(
			"AccoRateDef2AccoRateDetailDefRel", 
			false, 

			"accoRateDef", 
			"AccommodationRateDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"accoRateDetailDefs", 
			"AccoRateDetailDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.SET
		);
	
		createRelationAttributes(
			"AccoRateDetailDefinition2RoomTypeRateRel", 
			false, 

			"accoRateDetailDefinition", 
			"AccoRateDetailDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"roomTypeRates", 
			"RoomTypeRate", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.PARTOF_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.SET
		);
	
		createRelationAttributes(
			"CommonRateAdvDefinition2SupplierRoomOfferRel", 
			false, 

			"commonRateAdvDef", 
			"CommonRateAdvDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"supplierRoomOffers", 
			"SupplierRoomOffer", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.SET
		);
	
		createRelationAttributes(
			"AccoRateDef2AccoDynamicPolicyRel", 
			false, 

			"accRateDef", 
			"AccommodationRateDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION,
			"accoDynamicPolicies", 
			"AccoDynamicPolicy", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.SET
		);
	
		createRelationAttributes(
			"AccoRateDetailDefinition2AbstractTravelogixSupplierOfferRel", 
			false, 

			"accoRateDetailDefinition", 
			"AccoRateDetailDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION,
			"absTravelogixSupplierOffers", 
			"AbstractTravelogixSupplierOffer", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"AccoRateDetailDefinition2ChildAgeRateDetailRel", 
			false, 

			"accoRateDetailDefinition", 
			"AccoRateDetailDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"childRate", 
			"ChildAgeRateDetail", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.PARTOF_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	

	}

	
	public void single_createattr_AccommodationRateDefinition_priceApplicability() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccommodationRateDefinition", 
					"priceApplicability",  
					null,
					"PriceApplicabilityType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccommodationRateDefinition_noOfRooms() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccommodationRateDefinition", 
					"noOfRooms",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccommodationRateDefinition_comparator() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccommodationRateDefinition", 
					"comparator",  
					null,
					"AdvancedQueryComparatorEnum",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccommodationRateDefinition_surchargeSupplement() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccommodationRateDefinition", 
					"surchargeSupplement",  
					null,
					"AccoSurchargeSuppDetail",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_minNights() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"minNights",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_dayOfWeek() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"dayOfWeek",  
					null,
					"WeekDayCollection",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_rateDefinedFor() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"rateDefinedFor",  
					null,
					"RatesDefinedForType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_roomCategory() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"roomCategory",  
					null,
					"RoomCategory",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_proRata() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"proRata",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_stayDuration() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"stayDuration",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_rateFor() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"rateFor",  
					null,
					"Ratefor",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_mealPlan() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"mealPlan",  
					null,
					"MealPlanType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_checkInTime() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"checkInTime",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_checkOutTime() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"checkOutTime",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_commissionExcluded() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"commissionExcluded",  
					null,
					"RoomType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_childAge() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"childAge",  
					null,
					"AgeDetail",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_noOfChild() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"noOfChild",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_noOfAdults() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"noOfAdults",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_adultAge() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"adultAge",  
					null,
					"AgeDetail",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_rate() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"rate",  
					null,
					"java.lang.Double",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_minPaxOccupancy() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"minPaxOccupancy",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_maxPaxOccupancy() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"maxPaxOccupancy",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_payOnArrival() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"payOnArrival",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoRateDetailDefinition_commonRateAdvDefinition() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoRateDetailDefinition", 
					"commonRateAdvDefinition",  
					null,
					"CommonRateAdvDefinition",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_RoomTypeRate_rate() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"RoomTypeRate", 
					"rate",  
					null,
					"java.lang.Double",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_RoomTypeRate_roomType() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"RoomTypeRate", 
					"roomType",  
					null,
					"RoomType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_RoomTypeRate_payOnArrival() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"RoomTypeRate", 
					"payOnArrival",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoSurchargeSuppDetail_subType() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoSurchargeSuppDetail", 
					"subType",  
					null,
					"AccoSurchargeSubType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoSurchargeSuppDetail_roomCategories() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoSurchargeSuppDetail", 
					"roomCategories",  
					null,
					"RoomCategorySet",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoSurchargeSuppDetail_roomTypes() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoSurchargeSuppDetail", 
					"roomTypes",  
					null,
					"RoomTypeSet",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoSurchargeSuppDetail_mealPlan() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoSurchargeSuppDetail", 
					"mealPlan",  
					null,
					"MealPlanTypeSet",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoSurchargeSuppDetail_stdCommissionValue() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoSurchargeSuppDetail", 
					"stdCommissionValue",  
					null,
					"java.lang.Double",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoSurchargeSuppDetail_stdCommissionType() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoSurchargeSuppDetail", 
					"stdCommissionType",  
					null,
					"ThresholdType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoSurchargeSuppDetail_amount() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoSurchargeSuppDetail", 
					"amount",  
					null,
					"java.lang.Double",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_SupplierRoomOffer_roomCategory() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"SupplierRoomOffer", 
					"roomCategory",  
					null,
					"RoomCategory",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_SupplierRoomOffer_roomType() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"SupplierRoomOffer", 
					"roomType",  
					null,
					"RoomType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_SupplierRoomOffer_maxNoOfRooms() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"SupplierRoomOffer", 
					"maxNoOfRooms",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CommonAncillaryRateDetail_startTime() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CommonAncillaryRateDetail", 
					"startTime",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CommonAncillaryRateDetail_durationType() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CommonAncillaryRateDetail", 
					"durationType",  
					null,
					"DurationType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CommonAncillaryRateDetail_durationValue() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CommonAncillaryRateDetail", 
					"durationValue",  
					null,
					"java.lang.Double",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CommonAncillaryRateDetail_seatingType() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CommonAncillaryRateDetail", 
					"seatingType",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CommonAncillaryRateDetail_costApplicability() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CommonAncillaryRateDetail", 
					"costApplicability",  
					null,
					"PriceApplicabilityType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CommonAncillaryRateDetail_paxType() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CommonAncillaryRateDetail", 
					"paxType",  
					null,
					"PaxType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CommonAncillaryRateDetail_childAge() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CommonAncillaryRateDetail", 
					"childAge",  
					null,
					"AgeDetail",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CommonAncillaryRateDetail_vehicleType() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CommonAncillaryRateDetail", 
					"vehicleType",  
					null,
					"VehicleType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CommonAncillaryRateDetail_portName() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CommonAncillaryRateDetail", 
					"portName",  
					null,
					"CruisePort",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateObjects( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateObjects
	
	
		createEnumerationValues(
			"AccoSurchargeSubType",
			false,
			Arrays.asList( new String[] {
			
				"ROOM_LEVEL",
				"PAX_TYPE",
				"GUIDE",
				"MEAL_SUPPLEMENTS",
				"OTHERS"
			} )
		);
	
		createEnumerationValues(
			"ChildBedType",
			false,
			Arrays.asList( new String[] {
			
				"CHILD_NO_BED",
				"CHILD_WITH_EXTRA_BED"
			} )
		);
	
		createEnumerationValues(
			"RateFor",
			false,
			Arrays.asList( new String[] {
			
				"HOTEL",
				"HOTEL_PACKAGE"
			} )
		);
	
		createEnumerationValues(
			"MealPlanType",
			true,
			Arrays.asList( new String[] {
			
				"AI",
				"AP",
				"BB",
				"CP",
				"EP",
				"FP",
				"FA",
				"HP",
				"MAP"
			} )
		);
	
		createEnumerationValues(
			"DurationType",
			false,
			Arrays.asList( new String[] {
			
				"DAYS",
				"HOURS",
				"MINS"
			} )
		);
	
		createEnumerationValues(
			"VehicleType",
			false,
			Arrays.asList( new String[] {
			
				"FLIGHTS",
				"CARS",
				"CRUISE",
				"BUS",
				"RAIL_TICKETS",
				"RAIL_PASS"
			} )
		);
	
		single_setRelAttributeProperties_AccoRateDef2AccoRateDetailDefRel_source();
	
		single_setRelAttributeProperties_AccoRateDetailDefinition2RoomTypeRateRel_source();
	
		single_setRelAttributeProperties_CommonRateAdvDefinition2SupplierRoomOfferRel_source();
	
		single_setRelAttributeProperties_AccoRateDef2AccoDynamicPolicyRel_source();
	
		single_setRelAttributeProperties_AccoRateDetailDefinition2AbstractTravelogixSupplierOfferRel_source();
	
		single_setRelAttributeProperties_AccoRateDetailDefinition2ChildAgeRateDetailRel_source();
	
		single_setRelAttributeProperties_AccoRateDef2AccoRateDetailDefRel_target();
	
		single_setRelAttributeProperties_AccoRateDetailDefinition2RoomTypeRateRel_target();
	
		single_setRelAttributeProperties_CommonRateAdvDefinition2SupplierRoomOfferRel_target();
	
		single_setRelAttributeProperties_AccoRateDef2AccoDynamicPolicyRel_target();
	
		single_setRelAttributeProperties_AccoRateDetailDefinition2AbstractTravelogixSupplierOfferRel_target();
	
		single_setRelAttributeProperties_AccoRateDetailDefinition2ChildAgeRateDetailRel_target();
	
		connectRelation(
			"AccoRateDef2AccoRateDetailDefRel", 
			false, 
			"accoRateDef", 
			"AccommodationRateDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"accoRateDetailDefs", 
			"AccoRateDetailDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"AccoRateDetailDefinition2RoomTypeRateRel", 
			false, 
			"accoRateDetailDefinition", 
			"AccoRateDetailDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"roomTypeRates", 
			"RoomTypeRate", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.PARTOF_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"CommonRateAdvDefinition2SupplierRoomOfferRel", 
			false, 
			"commonRateAdvDef", 
			"CommonRateAdvDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"supplierRoomOffers", 
			"SupplierRoomOffer", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"AccoRateDef2AccoDynamicPolicyRel", 
			false, 
			"accRateDef", 
			"AccommodationRateDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"accoDynamicPolicies", 
			"AccoDynamicPolicy", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"AccoRateDetailDefinition2AbstractTravelogixSupplierOfferRel", 
			false, 
			"accoRateDetailDefinition", 
			"AccoRateDetailDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"absTravelogixSupplierOffers", 
			"AbstractTravelogixSupplierOffer", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"AccoRateDetailDefinition2ChildAgeRateDetailRel", 
			false, 
			"accoRateDetailDefinition", 
			"AccoRateDetailDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"childRate", 
			"ChildAgeRateDetail", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.PARTOF_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"AccommodationSupplierRate",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"AccommodationRateDefinition",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_AccommodationRateDefinition_priceApplicability();
		
			single_setAttributeProperties_AccommodationRateDefinition_noOfRooms();
		
			single_setAttributeProperties_AccommodationRateDefinition_comparator();
		
			single_setAttributeProperties_AccommodationRateDefinition_surchargeSupplement();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"AccoRateDetailDefinition",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_AccoRateDetailDefinition_minNights();
		
			single_setAttributeProperties_AccoRateDetailDefinition_dayOfWeek();
		
			single_setAttributeProperties_AccoRateDetailDefinition_rateDefinedFor();
		
			single_setAttributeProperties_AccoRateDetailDefinition_roomCategory();
		
			single_setAttributeProperties_AccoRateDetailDefinition_proRata();
		
			single_setAttributeProperties_AccoRateDetailDefinition_stayDuration();
		
			single_setAttributeProperties_AccoRateDetailDefinition_rateFor();
		
			single_setAttributeProperties_AccoRateDetailDefinition_mealPlan();
		
			single_setAttributeProperties_AccoRateDetailDefinition_checkInTime();
		
			single_setAttributeProperties_AccoRateDetailDefinition_checkOutTime();
		
			single_setAttributeProperties_AccoRateDetailDefinition_commissionExcluded();
		
			single_setAttributeProperties_AccoRateDetailDefinition_childAge();
		
			single_setAttributeProperties_AccoRateDetailDefinition_noOfChild();
		
			single_setAttributeProperties_AccoRateDetailDefinition_noOfAdults();
		
			single_setAttributeProperties_AccoRateDetailDefinition_adultAge();
		
			single_setAttributeProperties_AccoRateDetailDefinition_rate();
		
			single_setAttributeProperties_AccoRateDetailDefinition_minPaxOccupancy();
		
			single_setAttributeProperties_AccoRateDetailDefinition_maxPaxOccupancy();
		
			single_setAttributeProperties_AccoRateDetailDefinition_payOnArrival();
		
			single_setAttributeProperties_AccoRateDetailDefinition_commonRateAdvDefinition();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"RoomTypeRate",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_RoomTypeRate_rate();
		
			single_setAttributeProperties_RoomTypeRate_roomType();
		
			single_setAttributeProperties_RoomTypeRate_payOnArrival();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"AccoSurchargeSuppDetail",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_AccoSurchargeSuppDetail_subType();
		
			single_setAttributeProperties_AccoSurchargeSuppDetail_roomCategories();
		
			single_setAttributeProperties_AccoSurchargeSuppDetail_roomTypes();
		
			single_setAttributeProperties_AccoSurchargeSuppDetail_mealPlan();
		
			single_setAttributeProperties_AccoSurchargeSuppDetail_stdCommissionValue();
		
			single_setAttributeProperties_AccoSurchargeSuppDetail_stdCommissionType();
		
			single_setAttributeProperties_AccoSurchargeSuppDetail_amount();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"SupplierRoomOffer",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_SupplierRoomOffer_roomCategory();
		
			single_setAttributeProperties_SupplierRoomOffer_roomType();
		
			single_setAttributeProperties_SupplierRoomOffer_maxNoOfRooms();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"CommonAncillaryRateDetail",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_CommonAncillaryRateDetail_startTime();
		
			single_setAttributeProperties_CommonAncillaryRateDetail_durationType();
		
			single_setAttributeProperties_CommonAncillaryRateDetail_durationValue();
		
			single_setAttributeProperties_CommonAncillaryRateDetail_seatingType();
		
			single_setAttributeProperties_CommonAncillaryRateDetail_costApplicability();
		
			single_setAttributeProperties_CommonAncillaryRateDetail_paxType();
		
			single_setAttributeProperties_CommonAncillaryRateDetail_childAge();
		
			single_setAttributeProperties_CommonAncillaryRateDetail_vehicleType();
		
			single_setAttributeProperties_CommonAncillaryRateDetail_portName();
		
				setDefaultProperties(
					"RoomCategorySet",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"RoomTypeSet",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"MealPlanTypeSet",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"AccoSurchargeSubType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"ChildBedType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"RateFor",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"MealPlanType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"DurationType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"VehicleType",
					true,
					true,
					null
				);
			
	}


		
						public void single_setAttributeProperties_AccommodationRateDefinition_priceApplicability() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccommodationRateDefinition", 
								"priceApplicability",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccommodationRateDefinition_noOfRooms() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccommodationRateDefinition", 
								"noOfRooms",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccommodationRateDefinition_comparator() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccommodationRateDefinition", 
								"comparator",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccommodationRateDefinition_surchargeSupplement() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccommodationRateDefinition", 
								"surchargeSupplement",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_minNights() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"minNights",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_dayOfWeek() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"dayOfWeek",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_rateDefinedFor() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"rateDefinedFor",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_roomCategory() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"roomCategory",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_proRata() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"proRata",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_stayDuration() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"stayDuration",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_rateFor() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"rateFor",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_mealPlan() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"mealPlan",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_checkInTime() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"checkInTime",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_checkOutTime() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"checkOutTime",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_commissionExcluded() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"commissionExcluded",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_childAge() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"childAge",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_noOfChild() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"noOfChild",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_noOfAdults() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"noOfAdults",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_adultAge() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"adultAge",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_rate() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"rate",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_minPaxOccupancy() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"minPaxOccupancy",
								false, 
								Integer.valueOf(0),
								"Integer.valueOf(0)",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_maxPaxOccupancy() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"maxPaxOccupancy",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_payOnArrival() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"payOnArrival",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoRateDetailDefinition_commonRateAdvDefinition() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoRateDetailDefinition", 
								"commonRateAdvDefinition",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_RoomTypeRate_rate() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"RoomTypeRate", 
								"rate",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_RoomTypeRate_roomType() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"RoomTypeRate", 
								"roomType",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_RoomTypeRate_payOnArrival() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"RoomTypeRate", 
								"payOnArrival",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoSurchargeSuppDetail_subType() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoSurchargeSuppDetail", 
								"subType",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoSurchargeSuppDetail_roomCategories() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoSurchargeSuppDetail", 
								"roomCategories",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoSurchargeSuppDetail_roomTypes() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoSurchargeSuppDetail", 
								"roomTypes",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoSurchargeSuppDetail_mealPlan() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoSurchargeSuppDetail", 
								"mealPlan",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoSurchargeSuppDetail_stdCommissionValue() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoSurchargeSuppDetail", 
								"stdCommissionValue",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoSurchargeSuppDetail_stdCommissionType() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoSurchargeSuppDetail", 
								"stdCommissionType",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoSurchargeSuppDetail_amount() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoSurchargeSuppDetail", 
								"amount",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_SupplierRoomOffer_roomCategory() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"SupplierRoomOffer", 
								"roomCategory",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_SupplierRoomOffer_roomType() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"SupplierRoomOffer", 
								"roomType",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_SupplierRoomOffer_maxNoOfRooms() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"SupplierRoomOffer", 
								"maxNoOfRooms",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CommonAncillaryRateDetail_startTime() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CommonAncillaryRateDetail", 
								"startTime",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CommonAncillaryRateDetail_durationType() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CommonAncillaryRateDetail", 
								"durationType",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CommonAncillaryRateDetail_durationValue() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CommonAncillaryRateDetail", 
								"durationValue",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CommonAncillaryRateDetail_seatingType() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CommonAncillaryRateDetail", 
								"seatingType",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CommonAncillaryRateDetail_costApplicability() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CommonAncillaryRateDetail", 
								"costApplicability",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CommonAncillaryRateDetail_paxType() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CommonAncillaryRateDetail", 
								"paxType",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CommonAncillaryRateDetail_childAge() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CommonAncillaryRateDetail", 
								"childAge",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CommonAncillaryRateDetail_vehicleType() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CommonAncillaryRateDetail", 
								"vehicleType",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CommonAncillaryRateDetail_portName() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CommonAncillaryRateDetail", 
								"portName",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
								public void single_setRelAttributeProperties_AccoRateDef2AccoRateDetailDefRel_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"AccoRateDetailDefinition", 
										"accoRateDef",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_AccoRateDef2AccoRateDetailDefRel_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"AccommodationRateDefinition", 
										"accoRateDetailDefs",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_AccoRateDetailDefinition2RoomTypeRateRel_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"RoomTypeRate", 
										"accoRateDetailDefinition",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_AccoRateDetailDefinition2RoomTypeRateRel_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"AccoRateDetailDefinition", 
										"roomTypeRates",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_CommonRateAdvDefinition2SupplierRoomOfferRel_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"SupplierRoomOffer", 
										"commonRateAdvDef",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_CommonRateAdvDefinition2SupplierRoomOfferRel_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"CommonRateAdvDefinition", 
										"supplierRoomOffers",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_AccoRateDef2AccoDynamicPolicyRel_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"AccoDynamicPolicy", 
										"accRateDef",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_AccoRateDef2AccoDynamicPolicyRel_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"AccommodationRateDefinition", 
										"accoDynamicPolicies",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_AccoRateDetailDefinition2AbstractTravelogixSupplierOfferRel_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"AbstractTravelogixSupplierOffer", 
										"accoRateDetailDefinition",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_AccoRateDetailDefinition2AbstractTravelogixSupplierOfferRel_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"AccoRateDetailDefinition", 
										"absTravelogixSupplierOffers",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_AccoRateDetailDefinition2ChildAgeRateDetailRel_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"ChildAgeRateDetail", 
										"accoRateDetailDefinition",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_AccoRateDetailDefinition2ChildAgeRateDetailRel_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"AccoRateDetailDefinition", 
										"childRate",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
}

	