
package com.cnk.travelogix.custom.zif.terp.ws.complaints;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "zif_terp_ws_complaints_feedback", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/C:/CNK-Documents/SAP-Backend-Integration/WSDL/CRM/zif_terp_ws_complaints.wsdl")
public class ZifTerpWsComplaintsFeedback
    extends Service
{

    private final static URL ZIFTERPWSCOMPLAINTSFEEDBACK_WSDL_LOCATION;
    private final static WebServiceException ZIFTERPWSCOMPLAINTSFEEDBACK_EXCEPTION;
    private final static QName ZIFTERPWSCOMPLAINTSFEEDBACK_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "zif_terp_ws_complaints_feedback");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/CNK-Documents/SAP-Backend-Integration/WSDL/CRM/zif_terp_ws_complaints.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZIFTERPWSCOMPLAINTSFEEDBACK_WSDL_LOCATION = url;
        ZIFTERPWSCOMPLAINTSFEEDBACK_EXCEPTION = e;
    }

    public ZifTerpWsComplaintsFeedback() {
        super(__getWsdlLocation(), ZIFTERPWSCOMPLAINTSFEEDBACK_QNAME);
    }

    public ZifTerpWsComplaintsFeedback(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZIFTERPWSCOMPLAINTSFEEDBACK_QNAME, features);
    }

    public ZifTerpWsComplaintsFeedback(URL wsdlLocation) {
        super(wsdlLocation, ZIFTERPWSCOMPLAINTSFEEDBACK_QNAME);
    }

    public ZifTerpWsComplaintsFeedback(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZIFTERPWSCOMPLAINTSFEEDBACK_QNAME, features);
    }

    public ZifTerpWsComplaintsFeedback(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZifTerpWsComplaintsFeedback(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZIFERPWSCOMPLAINTSFEEDBACK
     */
    @WebEndpoint(name = "zif_terp_ws_complaints")
    public ZIFERPWSCOMPLAINTSFEEDBACK getZifTerpWsComplaints() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "zif_terp_ws_complaints"), ZIFERPWSCOMPLAINTSFEEDBACK.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZIFERPWSCOMPLAINTSFEEDBACK
     */
    @WebEndpoint(name = "zif_terp_ws_complaints")
    public ZIFERPWSCOMPLAINTSFEEDBACK getZifTerpWsComplaints(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "zif_terp_ws_complaints"), ZIFERPWSCOMPLAINTSFEEDBACK.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZIFTERPWSCOMPLAINTSFEEDBACK_EXCEPTION!= null) {
            throw ZIFTERPWSCOMPLAINTSFEEDBACK_EXCEPTION;
        }
        return ZIFTERPWSCOMPLAINTSFEEDBACK_WSDL_LOCATION;
    }

}
