

package holidayinventorycore;

import java.util.*;
import java.io.Serializable;
import de.hybris.platform.util.*;
import de.hybris.platform.core.*;
import de.hybris.platform.jalo.JaloBusinessException;
import de.hybris.platform.jalo.type.*;
import de.hybris.platform.persistence.type.*;
import de.hybris.platform.persistence.enumeration.*;
import de.hybris.platform.persistence.property.PersistenceManager;
import de.hybris.platform.persistence.*;

/**
 * Generated by hybris Platform.
 */
@SuppressWarnings({"cast","unused","boxing","null", "PMD"})
public class GeneratedTypeInitializer extends AbstractTypeInitializer
{
	/**
	 * Generated by hybris Platform.
	 */
	public GeneratedTypeInitializer( ManagerEJB manager, Map params )
	{
		super( manager, params );
	}


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected void performRemoveObjects( ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// no-op by now
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateTypes
	
	
		createItemType(
			"HolidayInventoryRequest",
			"AbstractInventoryRequest",
			com.cnk.travelogix.datamodel.holiday.inventory.jalo.HolidayInventoryRequest.class,
			"de.hybris.platform.persistence.holidayinventorycore_HolidayInventoryRequest",
			false,
			null,
			false
		);
	
		createItemType(
			"AbstractHolidayInventoryDetail",
			"AbstractInventoryDetail",
			com.cnk.travelogix.datamodel.holiday.inventory.jalo.AbstractHolidayInventoryDetail.class,
			null,
			false,
			null,
			true
		);
	
		createItemType(
			"HolidayInventoryDetail",
			"AbstractHolidayInventoryDetail",
			com.cnk.travelogix.datamodel.holiday.inventory.jalo.HolidayInventoryDetail.class,
			"de.hybris.platform.persistence.holidayinventorycore_HolidayInventoryDetail",
			false,
			null,
			false
		);
	
		createItemType(
			"PackageInclusionInfo",
			"GenericItem",
			com.cnk.travelogix.datamodel.holiday.inventory.jalo.PackageInclusionInfo.class,
			"de.hybris.platform.persistence.holidayinventorycore_PackageInclusionInfo",
			false,
			null,
			false
		);
	
		createItemType(
			"HolidayRoomInfo",
			"GenericItem",
			com.cnk.travelogix.datamodel.holiday.inventory.jalo.HolidayRoomInfo.class,
			"de.hybris.platform.persistence.holidayinventorycore_HolidayRoomInfo",
			false,
			null,
			false
		);
	
		createItemType(
			"HolidayDetailedRoomInfo",
			"HolidayRoomInfo",
			com.cnk.travelogix.datamodel.holiday.inventory.jalo.HolidayDetailedRoomInfo.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"HolidayRoomLevelInvDetail",
			"HolidayInventoryDetail",
			com.cnk.travelogix.datamodel.holiday.inventory.jalo.HolidayRoomLevelInvDetail.class,
			null,
			false,
			null,
			true
		);
	
		createItemType(
			"HolidayPaxRoomInvDetail",
			"HolidayRoomLevelInvDetail",
			com.cnk.travelogix.datamodel.holiday.inventory.jalo.HolidayPaxRoomInvDetail.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"HolidayAnyRoomInvDetail",
			"HolidayRoomLevelInvDetail",
			com.cnk.travelogix.datamodel.holiday.inventory.jalo.HolidayAnyRoomInvDetail.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"HolidayRoomTypeInvDetail",
			"HolidayRoomLevelInvDetail",
			com.cnk.travelogix.datamodel.holiday.inventory.jalo.HolidayRoomTypeInvDetail.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"TravelRangeHolidayInvDetails",
			"HolidayInventoryDetail",
			com.cnk.travelogix.datamodel.holiday.inventory.jalo.TravelRangeHolidayInvDetails.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"SpecificTravelDatesHolidayInvDetails",
			"HolidayInventoryDetail",
			com.cnk.travelogix.datamodel.holiday.inventory.jalo.SpecificTravelDatesHolidayInvDetails.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"HolidayCutOffAndCharges",
			"CutOffsAndCharges",
			com.cnk.travelogix.holiday.inventory.core.jalo.HolidayCutOffAndCharges.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"HolidayInvSupplierAdvanceDefinition",
			"GenericItem",
			com.cnk.travelogix.holiday.inventory.core.jalo.HolidayInvSupplierAdvanceDefinition.class,
			"de.hybris.platform.persistence.holidayinventorycore_HolidayInvSupplierAdvanceDefinition",
			false,
			null,
			false
		);
	
		createItemType(
			"HolidayInventoryDefinition",
			"AbstractInventoryDefinition",
			com.cnk.travelogix.holiday.inventory.core.jalo.HolidayInventoryDefinition.class,
			"de.hybris.platform.persistence.holidayinventorycore_HolidayInventoryDefinition",
			false,
			null,
			false
		);
	
		createItemType(
			"HolidayCompanySpecificInventory",
			"HolidayInventoryDetail",
			com.cnk.travelogix.holiday.inventory.core.jalo.HolidayCompanySpecificInventory.class,
			"de.hybris.platform.persistence.holidayinventorycore_HolidayCompanySpecificInventory",
			false,
			null,
			false
		);
	
		createItemType(
			"HolidayPenaltyCharges",
			"GenericItem",
			com.cnk.travelogix.holiday.inventory.core.jalo.HolidayPenaltyCharges.class,
			"de.hybris.platform.persistence.holidayinventorycore_HolidayPenaltyCharges",
			false,
			null,
			false
		);
	
		createRelationType(
			"HolidayInventoryDetailToHolidayRoomInfo",
			null,
			true
		);
	
		createRelationType(
			"HolidayInvSupplierAdvanceDefinition2HolidayPenaltyCharges",
			null,
			true
		);
	
		createRelationType(
			"HolidayInventoryDefinition2HolidayCompanySpecificInventory",
			null,
			true
		);
	
		createRelationType(
			"HolidayPenaltyCharges2HolidayCutOffAndCharges",
			null,
			true
		);
	
		createEnumerationType(
			"ValidForType",
			null
		);
	
		createEnumerationType(
			"InventoryRequestBy",
			null
		);
	
		createEnumerationType(
			"ThresholdApplicableOn",
			null
		);
	
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performModifyTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performModifyTypes
	

	
	
				single_createattr_HolidayInventoryRequest_product();
			
				single_createattr_HolidayInventoryRequest_productFlavour();
			
				single_createattr_HolidayInventoryRequest_priceRangeFrom();
			
				single_createattr_HolidayInventoryRequest_priceRangeTo();
			
				single_createattr_HolidayInventoryRequest_inventoryDefnitionCode();
			
				single_createattr_HolidayInventoryRequest_isFlightIncluded();
			
				single_createattr_HolidayInventoryRequest_packageCategory();
			
				single_createattr_AbstractHolidayInventoryDetail_noOfPax();
			
				single_createattr_AbstractHolidayInventoryDetail_anyRooms();
			
				single_createattr_AbstractHolidayInventoryDetail_roomTypeSingle();
			
				single_createattr_AbstractHolidayInventoryDetail_roomTypeDouble();
			
				single_createattr_AbstractHolidayInventoryDetail_roomTypeTriple();
			
				single_createattr_AbstractHolidayInventoryDetail_daysOfWeek();
			
				single_createattr_AbstractHolidayInventoryDetail_time();
			
				single_createattr_AbstractHolidayInventoryDetail_specificDates();
			
				single_createattr_AbstractHolidayInventoryDetail_travelDateRange();
			
				single_createattr_PackageInclusionInfo_serviceBasedDayWiseItineraries();
			
				single_createattr_PackageInclusionInfo_itineraryBasedDayWiseItineraries();
			
				single_createattr_HolidayRoomInfo_city();
			
				single_createattr_HolidayRoomInfo_checkInDate();
			
				single_createattr_HolidayRoomInfo_checkOutDate();
			
				single_createattr_HolidayRoomInfo_accommodation();
			
				single_createattr_HolidayRoomInfo_rating();
			
				single_createattr_HolidayRoomInfo_roomCategory();
			
				single_createattr_HolidayDetailedRoomInfo_noOfNights();
			
				single_createattr_HolidayDetailedRoomInfo_packageInclusion();
			
				single_createattr_HolidayPaxRoomInvDetail_noOfRooms();
			
				single_createattr_HolidayCutOffAndCharges_priceComponent();
			
				single_createattr_HolidayCutOffAndCharges_applicableOn();
			
				single_createattr_HolidayInvSupplierAdvanceDefinition_cutOffForFreeSale();
			
				single_createattr_HolidayInvSupplierAdvanceDefinition_blockOutDates();
			
				single_createattr_HolidayInventoryDefinition_overBookingLimit();
			
				single_createattr_HolidayInventoryDefinition_product();
			
				single_createattr_HolidayInventoryDefinition_flavor();
			
				single_createattr_HolidayInventoryDefinition_packageCategory();
			
				single_createattr_HolidayInventoryDefinition_market();
			
				single_createattr_HolidayInventoryDefinition_requestedBy();
			
				single_createattr_HolidayInventoryDefinition_advanceDefinition();
			
				single_createattr_HolidayCompanySpecificInventory_sbu();
			
				single_createattr_HolidayCompanySpecificInventory_bu();
			
				single_createattr_HolidayCompanySpecificInventory_market();
			
				single_createattr_HolidayCompanySpecificInventory_distributionChannel();
			
				single_createattr_HolidayCompanySpecificInventory_division();
			
				single_createattr_HolidayCompanySpecificInventory_salesOffice();
			
				single_createattr_HolidayCompanySpecificInventory_stopSales();
			
				single_createattr_HolidayCompanySpecificInventory_liabilityOnUtilization();
			
				single_createattr_HolidayPenaltyCharges_validateForType();
			
				single_createattr_HolidayPenaltyCharges_definedBy();
			
				single_createattr_HolidayPenaltyCharges_appliedOn();
			
				single_createattr_HolidayPenaltyCharges_thresholdAppliedOn();
			
		createRelationAttributes(
			"HolidayInventoryDetailToHolidayRoomInfo", 
			false, 

			"holidayInventoryDetail", 
			"HolidayInventoryDetail", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"holidayProductRoomInfo", 
			"HolidayRoomInfo", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"HolidayInvSupplierAdvanceDefinition2HolidayPenaltyCharges", 
			false, 

			"HolidayInvSupplierAdvanceDefinition", 
			"HolidayInvSupplierAdvanceDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"penaltyCharges", 
			"HolidayPenaltyCharges", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"HolidayInventoryDefinition2HolidayCompanySpecificInventory", 
			false, 

			"holidayInventoryDefinition", 
			"HolidayInventoryDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"distributedInventories", 
			"HolidayCompanySpecificInventory", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"HolidayPenaltyCharges2HolidayCutOffAndCharges", 
			false, 

			"holidayPenaltyCharges", 
			"HolidayPenaltyCharges", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"charges", 
			"HolidayCutOffAndCharges", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	

	}

	
	public void single_createattr_HolidayInventoryRequest_product() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryRequest", 
					"product",  
					null,
					"HolidayProduct",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryRequest_productFlavour() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryRequest", 
					"productFlavour",  
					null,
					"HolidayFlavor",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryRequest_priceRangeFrom() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryRequest", 
					"priceRangeFrom",  
					null,
					"java.math.BigDecimal",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryRequest_priceRangeTo() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryRequest", 
					"priceRangeTo",  
					null,
					"java.math.BigDecimal",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryRequest_inventoryDefnitionCode() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryRequest", 
					"inventoryDefnitionCode",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryRequest_isFlightIncluded() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryRequest", 
					"isFlightIncluded",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryRequest_packageCategory() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryRequest", 
					"packageCategory",  
					null,
					"PackageCategory",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractHolidayInventoryDetail_noOfPax() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractHolidayInventoryDetail", 
					"noOfPax",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractHolidayInventoryDetail_anyRooms() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractHolidayInventoryDetail", 
					"anyRooms",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractHolidayInventoryDetail_roomTypeSingle() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractHolidayInventoryDetail", 
					"roomTypeSingle",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractHolidayInventoryDetail_roomTypeDouble() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractHolidayInventoryDetail", 
					"roomTypeDouble",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractHolidayInventoryDetail_roomTypeTriple() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractHolidayInventoryDetail", 
					"roomTypeTriple",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractHolidayInventoryDetail_daysOfWeek() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractHolidayInventoryDetail", 
					"daysOfWeek",  
					null,
					"WeekDayCollection",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractHolidayInventoryDetail_time() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractHolidayInventoryDetail", 
					"time",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractHolidayInventoryDetail_specificDates() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractHolidayInventoryDetail", 
					"specificDates",  
					null,
					"DateCollection",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractHolidayInventoryDetail_travelDateRange() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractHolidayInventoryDetail", 
					"travelDateRange",  
					null,
					"de.hybris.platform.util.StandardDateRange",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PackageInclusionInfo_serviceBasedDayWiseItineraries() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PackageInclusionInfo", 
					"serviceBasedDayWiseItineraries",  
					null,
					"AbstractDayWiseItinerary",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PackageInclusionInfo_itineraryBasedDayWiseItineraries() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PackageInclusionInfo", 
					"itineraryBasedDayWiseItineraries",  
					null,
					"DayWiseItinerary",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayRoomInfo_city() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayRoomInfo", 
					"city",  
					null,
					"City",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayRoomInfo_checkInDate() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayRoomInfo", 
					"checkInDate",  
					null,
					"java.util.Date",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayRoomInfo_checkOutDate() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayRoomInfo", 
					"checkOutDate",  
					null,
					"java.util.Date",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayRoomInfo_accommodation() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayRoomInfo", 
					"accommodation",  
					null,
					"Accommodation",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayRoomInfo_rating() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayRoomInfo", 
					"rating",  
					null,
					"Rating",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayRoomInfo_roomCategory() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayRoomInfo", 
					"roomCategory",  
					null,
					"RoomCategory",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayDetailedRoomInfo_noOfNights() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayDetailedRoomInfo", 
					"noOfNights",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayDetailedRoomInfo_packageInclusion() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayDetailedRoomInfo", 
					"packageInclusion",  
					null,
					"PackageInclusionInfo",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayPaxRoomInvDetail_noOfRooms() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayPaxRoomInvDetail", 
					"noOfRooms",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayCutOffAndCharges_priceComponent() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayCutOffAndCharges", 
					"priceComponent",  
					null,
					"NonAirPriceComponentType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayCutOffAndCharges_applicableOn() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayCutOffAndCharges", 
					"applicableOn",  
					null,
					"ThresholdApplicableOn",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInvSupplierAdvanceDefinition_cutOffForFreeSale() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInvSupplierAdvanceDefinition", 
					"cutOffForFreeSale",  
					null,
					"CutOffForFreeSale",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInvSupplierAdvanceDefinition_blockOutDates() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInvSupplierAdvanceDefinition", 
					"blockOutDates",  
					null,
					"StandardDateRangeSet",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryDefinition_overBookingLimit() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryDefinition", 
					"overBookingLimit",  
					null,
					"java.lang.Long",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryDefinition_product() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryDefinition", 
					"product",  
					null,
					"HolidayProduct",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryDefinition_flavor() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryDefinition", 
					"flavor",  
					null,
					"HolidayFlavor",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryDefinition_packageCategory() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryDefinition", 
					"packageCategory",  
					null,
					"PackageCategory",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryDefinition_market() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryDefinition", 
					"market",  
					null,
					"Market",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryDefinition_requestedBy() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryDefinition", 
					"requestedBy",  
					null,
					"InventoryRequestBy",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayInventoryDefinition_advanceDefinition() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayInventoryDefinition", 
					"advanceDefinition",  
					null,
					"HolidayInvSupplierAdvanceDefinition",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayCompanySpecificInventory_sbu() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayCompanySpecificInventory", 
					"sbu",  
					null,
					"StrategicBusinessUnit",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayCompanySpecificInventory_bu() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayCompanySpecificInventory", 
					"bu",  
					null,
					"BusinessUnit",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayCompanySpecificInventory_market() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayCompanySpecificInventory", 
					"market",  
					null,
					"Market",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayCompanySpecificInventory_distributionChannel() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayCompanySpecificInventory", 
					"distributionChannel",  
					null,
					"DistributionChannel",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayCompanySpecificInventory_division() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayCompanySpecificInventory", 
					"division",  
					null,
					"Division",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayCompanySpecificInventory_salesOffice() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayCompanySpecificInventory", 
					"salesOffice",  
					null,
					"SalesOffice",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayCompanySpecificInventory_stopSales() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayCompanySpecificInventory", 
					"stopSales",  
					null,
					"java.Lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayCompanySpecificInventory_liabilityOnUtilization() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayCompanySpecificInventory", 
					"liabilityOnUtilization",  
					null,
					"java.Lang.Double",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayPenaltyCharges_validateForType() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayPenaltyCharges", 
					"validateForType",  
					null,
					"ValidForType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayPenaltyCharges_definedBy() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayPenaltyCharges", 
					"definedBy",  
					null,
					"DefinedBy",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayPenaltyCharges_appliedOn() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayPenaltyCharges", 
					"appliedOn",  
					null,
					"AppliedOn",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidayPenaltyCharges_thresholdAppliedOn() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidayPenaltyCharges", 
					"thresholdAppliedOn",  
					null,
					"ThresholdApplicableOn",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateObjects( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateObjects
	
	
		createEnumerationValues(
			"ValidForType",
			false,
			Arrays.asList( new String[] {
			
				"ALL_TOUR_DATES",
				"SPECIFIC_TOUR_DATES"
			} )
		);
	
		createEnumerationValues(
			"InventoryRequestBy",
			false,
			Arrays.asList( new String[] {
			
				"PAX",
				"ROOMS"
			} )
		);
	
		createEnumerationValues(
			"ThresholdApplicableOn",
			false,
			Arrays.asList( new String[] {
			
				"TOUR_DATE",
				"TOTAL_UTILIZATION"
			} )
		);
	
		single_setRelAttributeProperties_HolidayInventoryDetailToHolidayRoomInfo_source();
	
		single_setRelAttributeProperties_HolidayInvSupplierAdvanceDefinition2HolidayPenaltyCharges_source();
	
		single_setRelAttributeProperties_HolidayInventoryDefinition2HolidayCompanySpecificInventory_source();
	
		single_setRelAttributeProperties_HolidayPenaltyCharges2HolidayCutOffAndCharges_source();
	
		single_setRelAttributeProperties_HolidayInventoryDetailToHolidayRoomInfo_target();
	
		single_setRelAttributeProperties_HolidayInvSupplierAdvanceDefinition2HolidayPenaltyCharges_target();
	
		single_setRelAttributeProperties_HolidayInventoryDefinition2HolidayCompanySpecificInventory_target();
	
		single_setRelAttributeProperties_HolidayPenaltyCharges2HolidayCutOffAndCharges_target();
	
		connectRelation(
			"HolidayInventoryDetailToHolidayRoomInfo", 
			false, 
			"holidayInventoryDetail", 
			"HolidayInventoryDetail", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"holidayProductRoomInfo", 
			"HolidayRoomInfo", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"HolidayInvSupplierAdvanceDefinition2HolidayPenaltyCharges", 
			false, 
			"HolidayInvSupplierAdvanceDefinition", 
			"HolidayInvSupplierAdvanceDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"penaltyCharges", 
			"HolidayPenaltyCharges", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"HolidayInventoryDefinition2HolidayCompanySpecificInventory", 
			false, 
			"holidayInventoryDefinition", 
			"HolidayInventoryDefinition", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"distributedInventories", 
			"HolidayCompanySpecificInventory", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"HolidayPenaltyCharges2HolidayCutOffAndCharges", 
			false, 
			"holidayPenaltyCharges", 
			"HolidayPenaltyCharges", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"charges", 
			"HolidayCutOffAndCharges", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayInventoryRequest",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_HolidayInventoryRequest_product();
		
			single_setAttributeProperties_HolidayInventoryRequest_productFlavour();
		
			single_setAttributeProperties_HolidayInventoryRequest_priceRangeFrom();
		
			single_setAttributeProperties_HolidayInventoryRequest_priceRangeTo();
		
			single_setAttributeProperties_HolidayInventoryRequest_inventoryDefnitionCode();
		
			single_setAttributeProperties_HolidayInventoryRequest_isFlightIncluded();
		
			single_setAttributeProperties_HolidayInventoryRequest_packageCategory();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"AbstractHolidayInventoryDetail",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_AbstractHolidayInventoryDetail_noOfPax();
		
			single_setAttributeProperties_AbstractHolidayInventoryDetail_anyRooms();
		
			single_setAttributeProperties_AbstractHolidayInventoryDetail_roomTypeSingle();
		
			single_setAttributeProperties_AbstractHolidayInventoryDetail_roomTypeDouble();
		
			single_setAttributeProperties_AbstractHolidayInventoryDetail_roomTypeTriple();
		
			single_setAttributeProperties_AbstractHolidayInventoryDetail_daysOfWeek();
		
			single_setAttributeProperties_AbstractHolidayInventoryDetail_time();
		
			single_setAttributeProperties_AbstractHolidayInventoryDetail_specificDates();
		
			single_setAttributeProperties_AbstractHolidayInventoryDetail_travelDateRange();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayInventoryDetail",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PackageInclusionInfo",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_PackageInclusionInfo_serviceBasedDayWiseItineraries();
		
			single_setAttributeProperties_PackageInclusionInfo_itineraryBasedDayWiseItineraries();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayRoomInfo",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_HolidayRoomInfo_city();
		
			single_setAttributeProperties_HolidayRoomInfo_checkInDate();
		
			single_setAttributeProperties_HolidayRoomInfo_checkOutDate();
		
			single_setAttributeProperties_HolidayRoomInfo_accommodation();
		
			single_setAttributeProperties_HolidayRoomInfo_rating();
		
			single_setAttributeProperties_HolidayRoomInfo_roomCategory();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayDetailedRoomInfo",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_HolidayDetailedRoomInfo_noOfNights();
		
			single_setAttributeProperties_HolidayDetailedRoomInfo_packageInclusion();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayRoomLevelInvDetail",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayPaxRoomInvDetail",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_HolidayPaxRoomInvDetail_noOfRooms();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayAnyRoomInvDetail",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayRoomTypeInvDetail",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"TravelRangeHolidayInvDetails",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"SpecificTravelDatesHolidayInvDetails",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayCutOffAndCharges",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_HolidayCutOffAndCharges_priceComponent();
		
			single_setAttributeProperties_HolidayCutOffAndCharges_applicableOn();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayInvSupplierAdvanceDefinition",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_HolidayInvSupplierAdvanceDefinition_cutOffForFreeSale();
		
			single_setAttributeProperties_HolidayInvSupplierAdvanceDefinition_blockOutDates();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayInventoryDefinition",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_HolidayInventoryDefinition_overBookingLimit();
		
			single_setAttributeProperties_HolidayInventoryDefinition_product();
		
			single_setAttributeProperties_HolidayInventoryDefinition_flavor();
		
			single_setAttributeProperties_HolidayInventoryDefinition_packageCategory();
		
			single_setAttributeProperties_HolidayInventoryDefinition_market();
		
			single_setAttributeProperties_HolidayInventoryDefinition_requestedBy();
		
			single_setAttributeProperties_HolidayInventoryDefinition_advanceDefinition();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayCompanySpecificInventory",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_HolidayCompanySpecificInventory_sbu();
		
			single_setAttributeProperties_HolidayCompanySpecificInventory_bu();
		
			single_setAttributeProperties_HolidayCompanySpecificInventory_market();
		
			single_setAttributeProperties_HolidayCompanySpecificInventory_distributionChannel();
		
			single_setAttributeProperties_HolidayCompanySpecificInventory_division();
		
			single_setAttributeProperties_HolidayCompanySpecificInventory_salesOffice();
		
			single_setAttributeProperties_HolidayCompanySpecificInventory_stopSales();
		
			single_setAttributeProperties_HolidayCompanySpecificInventory_liabilityOnUtilization();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidayPenaltyCharges",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_HolidayPenaltyCharges_validateForType();
		
			single_setAttributeProperties_HolidayPenaltyCharges_definedBy();
		
			single_setAttributeProperties_HolidayPenaltyCharges_appliedOn();
		
			single_setAttributeProperties_HolidayPenaltyCharges_thresholdAppliedOn();
		
				setDefaultProperties(
					"ValidForType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"InventoryRequestBy",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"ThresholdApplicableOn",
					true,
					true,
					null
				);
			
	}


		
						public void single_setAttributeProperties_HolidayInventoryRequest_product() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryRequest", 
								"product",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryRequest_productFlavour() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryRequest", 
								"productFlavour",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryRequest_priceRangeFrom() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryRequest", 
								"priceRangeFrom",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryRequest_priceRangeTo() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryRequest", 
								"priceRangeTo",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryRequest_inventoryDefnitionCode() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryRequest", 
								"inventoryDefnitionCode",
								true, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryRequest_isFlightIncluded() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryRequest", 
								"isFlightIncluded",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryRequest_packageCategory() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryRequest", 
								"packageCategory",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractHolidayInventoryDetail_noOfPax() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractHolidayInventoryDetail", 
								"noOfPax",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractHolidayInventoryDetail_anyRooms() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractHolidayInventoryDetail", 
								"anyRooms",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractHolidayInventoryDetail_roomTypeSingle() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractHolidayInventoryDetail", 
								"roomTypeSingle",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractHolidayInventoryDetail_roomTypeDouble() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractHolidayInventoryDetail", 
								"roomTypeDouble",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractHolidayInventoryDetail_roomTypeTriple() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractHolidayInventoryDetail", 
								"roomTypeTriple",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractHolidayInventoryDetail_daysOfWeek() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractHolidayInventoryDetail", 
								"daysOfWeek",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractHolidayInventoryDetail_time() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractHolidayInventoryDetail", 
								"time",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractHolidayInventoryDetail_specificDates() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractHolidayInventoryDetail", 
								"specificDates",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractHolidayInventoryDetail_travelDateRange() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractHolidayInventoryDetail", 
								"travelDateRange",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PackageInclusionInfo_serviceBasedDayWiseItineraries() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PackageInclusionInfo", 
								"serviceBasedDayWiseItineraries",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PackageInclusionInfo_itineraryBasedDayWiseItineraries() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PackageInclusionInfo", 
								"itineraryBasedDayWiseItineraries",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayRoomInfo_city() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayRoomInfo", 
								"city",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayRoomInfo_checkInDate() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayRoomInfo", 
								"checkInDate",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayRoomInfo_checkOutDate() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayRoomInfo", 
								"checkOutDate",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayRoomInfo_accommodation() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayRoomInfo", 
								"accommodation",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayRoomInfo_rating() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayRoomInfo", 
								"rating",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayRoomInfo_roomCategory() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayRoomInfo", 
								"roomCategory",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayDetailedRoomInfo_noOfNights() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayDetailedRoomInfo", 
								"noOfNights",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayDetailedRoomInfo_packageInclusion() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayDetailedRoomInfo", 
								"packageInclusion",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayPaxRoomInvDetail_noOfRooms() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayPaxRoomInvDetail", 
								"noOfRooms",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayCutOffAndCharges_priceComponent() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayCutOffAndCharges", 
								"priceComponent",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayCutOffAndCharges_applicableOn() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayCutOffAndCharges", 
								"applicableOn",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInvSupplierAdvanceDefinition_cutOffForFreeSale() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInvSupplierAdvanceDefinition", 
								"cutOffForFreeSale",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInvSupplierAdvanceDefinition_blockOutDates() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInvSupplierAdvanceDefinition", 
								"blockOutDates",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryDefinition_overBookingLimit() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryDefinition", 
								"overBookingLimit",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryDefinition_product() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryDefinition", 
								"product",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryDefinition_flavor() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryDefinition", 
								"flavor",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryDefinition_packageCategory() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryDefinition", 
								"packageCategory",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryDefinition_market() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryDefinition", 
								"market",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryDefinition_requestedBy() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryDefinition", 
								"requestedBy",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayInventoryDefinition_advanceDefinition() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayInventoryDefinition", 
								"advanceDefinition",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayCompanySpecificInventory_sbu() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayCompanySpecificInventory", 
								"sbu",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayCompanySpecificInventory_bu() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayCompanySpecificInventory", 
								"bu",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayCompanySpecificInventory_market() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayCompanySpecificInventory", 
								"market",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayCompanySpecificInventory_distributionChannel() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayCompanySpecificInventory", 
								"distributionChannel",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayCompanySpecificInventory_division() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayCompanySpecificInventory", 
								"division",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayCompanySpecificInventory_salesOffice() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayCompanySpecificInventory", 
								"salesOffice",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayCompanySpecificInventory_stopSales() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayCompanySpecificInventory", 
								"stopSales",
								false, 
								java.lang.Boolean.FALSE,
								"java.lang.Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayCompanySpecificInventory_liabilityOnUtilization() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayCompanySpecificInventory", 
								"liabilityOnUtilization",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayPenaltyCharges_validateForType() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayPenaltyCharges", 
								"validateForType",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayPenaltyCharges_definedBy() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayPenaltyCharges", 
								"definedBy",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayPenaltyCharges_appliedOn() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayPenaltyCharges", 
								"appliedOn",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidayPenaltyCharges_thresholdAppliedOn() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidayPenaltyCharges", 
								"thresholdAppliedOn",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
								public void single_setRelAttributeProperties_HolidayInventoryDetailToHolidayRoomInfo_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"HolidayRoomInfo", 
										"holidayInventoryDetail",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_HolidayInventoryDetailToHolidayRoomInfo_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"HolidayInventoryDetail", 
										"holidayProductRoomInfo",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_HolidayInvSupplierAdvanceDefinition2HolidayPenaltyCharges_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"HolidayPenaltyCharges", 
										"HolidayInvSupplierAdvanceDefinition",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_HolidayInvSupplierAdvanceDefinition2HolidayPenaltyCharges_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"HolidayInvSupplierAdvanceDefinition", 
										"penaltyCharges",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_HolidayInventoryDefinition2HolidayCompanySpecificInventory_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"HolidayCompanySpecificInventory", 
										"holidayInventoryDefinition",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_HolidayInventoryDefinition2HolidayCompanySpecificInventory_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"HolidayInventoryDefinition", 
										"distributedInventories",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_HolidayPenaltyCharges2HolidayCutOffAndCharges_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"HolidayCutOffAndCharges", 
										"holidayPenaltyCharges",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_HolidayPenaltyCharges2HolidayCutOffAndCharges_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"HolidayPenaltyCharges", 
										"charges",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
}

	