//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.15 at 04:17:23 PM IST
//

package com.cnk.travelogix.core.sms.client.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MID">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="SUBMITDATE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="TAG" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="TID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="REQUEST-ERROR">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ERROR">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DESC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="REQID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "mid", "requesterror" })
@XmlRootElement(name = "RESULT")
public class NetcoreResponse {

    @XmlElement(name = "MID", required = true)
    protected NetcoreResponse.MID mid;
    @XmlElement(name = "REQUEST-ERROR", required = true)
    protected NetcoreResponse.REQUESTERROR requesterror;
    @XmlAttribute(name = "REQID")
    protected String reqid;

    /**
     * Gets the value of the mid property.
     *
     * @return possible object is {@link NetcoreResponse.MID }
     *
     */
    public NetcoreResponse.MID getMID() {
	return mid;
    }

    /**
     * Sets the value of the mid property.
     *
     * @param value
     *            allowed object is {@link NetcoreResponse.MID }
     *
     */
    public void setMID(final NetcoreResponse.MID value) {
	this.mid = value;
    }

    /**
     * Gets the value of the requesterror property.
     *
     * @return possible object is {@link NetcoreResponse.REQUESTERROR }
     *
     */
    public NetcoreResponse.REQUESTERROR getREQUESTERROR() {
	return requesterror;
    }

    /**
     * Sets the value of the requesterror property.
     *
     * @param value
     *            allowed object is {@link NetcoreResponse.REQUESTERROR }
     *
     */
    public void setREQUESTERROR(final NetcoreResponse.REQUESTERROR value) {
	this.requesterror = value;
    }

    /**
     * Gets the value of the reqid property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getREQID() {
	return reqid;
    }

    /**
     * Sets the value of the reqid property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setREQID(final String value) {
	this.reqid = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="SUBMITDATE" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="TAG" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="TID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class MID {

	@XmlValue
	protected String value;
	@XmlAttribute(name = "SUBMITDATE")
	protected String submitdate;
	@XmlAttribute(name = "ID")
	protected String id;
	@XmlAttribute(name = "TAG")
	protected String tag;
	@XmlAttribute(name = "TID")
	protected String tid;

	/**
	 * Gets the value of the value property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getValue() {
	    return value;
	}

	/**
	 * Sets the value of the value property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setValue(final String value) {
	    this.value = value;
	}

	/**
	 * Gets the value of the submitdate property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSUBMITDATE() {
	    return submitdate;
	}

	/**
	 * Sets the value of the submitdate property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setSUBMITDATE(final String value) {
	    this.submitdate = value;
	}

	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getID() {
	    return id;
	}

	/**
	 * Sets the value of the id property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setID(final String value) {
	    this.id = value;
	}

	/**
	 * Gets the value of the tag property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getTAG() {
	    return tag;
	}

	/**
	 * Sets the value of the tag property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setTAG(final String value) {
	    this.tag = value;
	}

	/**
	 * Gets the value of the tid property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getTID() {
	    return tid;
	}

	/**
	 * Sets the value of the tid property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setTID(final String value) {
	    this.tid = value;
	}

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ERROR">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DESC" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "error" })
    public static class REQUESTERROR {

	@XmlElement(name = "ERROR", required = true)
	protected NetcoreResponse.REQUESTERROR.ERROR error;

	/**
	 * Gets the value of the error property.
	 *
	 * @return possible object is
	 *         {@link NetcoreResponse.REQUESTERROR.ERROR }
	 *
	 */
	public NetcoreResponse.REQUESTERROR.ERROR getERROR() {
	    return error;
	}

	/**
	 * Sets the value of the error property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link NetcoreResponse.REQUESTERROR.ERROR }
	 *
	 */
	public void setERROR(final NetcoreResponse.REQUESTERROR.ERROR value) {
	    this.error = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content
	 * contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="DESC" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "code", "desc" })
	public static class ERROR {

	    @XmlElement(name = "CODE", required = true)
	    protected String code;
	    @XmlElement(name = "DESC", required = true)
	    protected String desc;

	    /**
	     * Gets the value of the code property.
	     *
	     * @return possible object is {@link String }
	     *
	     */
	    public String getCODE() {
		return code;
	    }

	    /**
	     * Sets the value of the code property.
	     *
	     * @param value
	     *            allowed object is {@link String }
	     *
	     */
	    public void setCODE(final String value) {
		this.code = value;
	    }

	    /**
	     * Gets the value of the desc property.
	     *
	     * @return possible object is {@link String }
	     *
	     */
	    public String getDESC() {
		return desc;
	    }

	    /**
	     * Sets the value of the desc property.
	     *
	     * @param value
	     *            allowed object is {@link String }
	     *
	     */
	    public void setDESC(final String value) {
		this.desc = value;
	    }

	    @Override
	    public String toString() {
		return "ERROR [code=" + code + ", desc=" + desc + "]";
	    }
	}

	@Override
	public String toString() {
	    return "REQUESTERROR [error=" + error + "]";
	}
    }

    @Override
    public String toString() {
	return "NetcoreResponse [mid=" + mid + ", requesterror=" + requesterror + ", reqid=" + reqid + "]";
    }
}
