//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.27 at 10:37:23 PM IST
//


package com.cnk.travelogix.fraud.beans.updatestatus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Update" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReferenceNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TxnLogID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="TemplateID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CreatedOn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="RiskLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RiskPercentage" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="PaymentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsFraud" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsChargeback" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder =
{ "update", "referenceNo", "txnLogID", "templateID", "createdOn", "amount", "riskLevel", "riskPercentage", "paymentStatus",
		"isFraud", "isChargeback" })
@XmlRootElement(name = "RMSIDResult")
public class RMSIDResult
{

	@XmlElement(name = "Update", required = true)
	protected String update;
	@XmlElement(name = "ReferenceNo", required = true)
	protected String referenceNo;
	@XmlElement(name = "TxnLogID")
	protected byte txnLogID;
	@XmlElement(name = "TemplateID", required = true)
	protected String templateID;
	@XmlElement(name = "CreatedOn", required = true)
	protected String createdOn;
	@XmlElement(name = "Amount")
	protected byte amount;
	@XmlElement(name = "RiskLevel", required = true)
	protected String riskLevel;
	@XmlElement(name = "RiskPercentage")
	protected float riskPercentage;
	@XmlElement(name = "PaymentStatus", required = true)
	protected String paymentStatus;
	@XmlElement(name = "IsFraud", required = true)
	protected String isFraud;
	@XmlElement(name = "IsChargeback", required = true)
	protected String isChargeback;

	/**
	 * Gets the value of the update property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUpdate()
	{
		return update;
	}

	/**
	 * Sets the value of the update property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setUpdate(final String value)
	{
		this.update = value;
	}

	/**
	 * Gets the value of the referenceNo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReferenceNo()
	{
		return referenceNo;
	}

	/**
	 * Sets the value of the referenceNo property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setReferenceNo(final String value)
	{
		this.referenceNo = value;
	}

	/**
	 * Gets the value of the txnLogID property.
	 * 
	 */
	public byte getTxnLogID()
	{
		return txnLogID;
	}

	/**
	 * Sets the value of the txnLogID property.
	 * 
	 */
	public void setTxnLogID(final byte value)
	{
		this.txnLogID = value;
	}

	/**
	 * Gets the value of the templateID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTemplateID()
	{
		return templateID;
	}

	/**
	 * Sets the value of the templateID property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setTemplateID(final String value)
	{
		this.templateID = value;
	}

	/**
	 * Gets the value of the createdOn property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCreatedOn()
	{
		return createdOn;
	}

	/**
	 * Sets the value of the createdOn property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setCreatedOn(final String value)
	{
		this.createdOn = value;
	}

	/**
	 * Gets the value of the amount property.
	 * 
	 */
	public byte getAmount()
	{
		return amount;
	}

	/**
	 * Sets the value of the amount property.
	 * 
	 */
	public void setAmount(final byte value)
	{
		this.amount = value;
	}

	/**
	 * Gets the value of the riskLevel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRiskLevel()
	{
		return riskLevel;
	}

	/**
	 * Sets the value of the riskLevel property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setRiskLevel(final String value)
	{
		this.riskLevel = value;
	}

	/**
	 * Gets the value of the riskPercentage property.
	 * 
	 */
	public float getRiskPercentage()
	{
		return riskPercentage;
	}

	/**
	 * Sets the value of the riskPercentage property.
	 * 
	 */
	public void setRiskPercentage(final float value)
	{
		this.riskPercentage = value;
	}

	/**
	 * Gets the value of the paymentStatus property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaymentStatus()
	{
		return paymentStatus;
	}

	/**
	 * Sets the value of the paymentStatus property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setPaymentStatus(final String value)
	{
		this.paymentStatus = value;
	}

	/**
	 * Gets the value of the isFraud property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIsFraud()
	{
		return isFraud;
	}

	/**
	 * Sets the value of the isFraud property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setIsFraud(final String value)
	{
		this.isFraud = value;
	}

	/**
	 * Gets the value of the isChargeback property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIsChargeback()
	{
		return isChargeback;
	}

	/**
	 * Sets the value of the isChargeback property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setIsChargeback(final String value)
	{
		this.isChargeback = value;
	}

}
