
package com.cnk.travelogix.custom.subscribe.account;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "suacProvisioning", targetNamespace = "http://provisioning.ws.highdeal.com/", wsdlLocation = "http://10.24.2.100:9080/suacProvisioning?WSDL")
public class SuacProvisioning
    extends Service
{

    private final static URL SUACPROVISIONING_WSDL_LOCATION;
    private final static WebServiceException SUACPROVISIONING_EXCEPTION;
    private final static QName SUACPROVISIONING_QNAME = new QName("http://provisioning.ws.highdeal.com/", "suacProvisioning");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.24.2.100:9080/suacProvisioning?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUACPROVISIONING_WSDL_LOCATION = url;
        SUACPROVISIONING_EXCEPTION = e;
    }

    public SuacProvisioning() {
        super(__getWsdlLocation(), SUACPROVISIONING_QNAME);
    }

    public SuacProvisioning(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUACPROVISIONING_QNAME, features);
    }

    public SuacProvisioning(URL wsdlLocation) {
        super(wsdlLocation, SUACPROVISIONING_QNAME);
    }

    public SuacProvisioning(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUACPROVISIONING_QNAME, features);
    }

    public SuacProvisioning(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SuacProvisioning(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SUACProvisioningServices
     */
    @WebEndpoint(name = "suacProvisioningPort")
    public SUACProvisioningServices getSuacProvisioningPort() {
        return super.getPort(new QName("http://provisioning.ws.highdeal.com/", "suacProvisioningPort"), SUACProvisioningServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SUACProvisioningServices
     */
    @WebEndpoint(name = "suacProvisioningPort")
    public SUACProvisioningServices getSuacProvisioningPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://provisioning.ws.highdeal.com/", "suacProvisioningPort"), SUACProvisioningServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUACPROVISIONING_EXCEPTION!= null) {
            throw SUACPROVISIONING_EXCEPTION;
        }
        return SUACPROVISIONING_WSDL_LOCATION;
    }

}
