
package com.cnk.travelogix.custom.zif.erp.ws.custmastercreate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZIF_ERP_WS_CUSTOMER_CREATE", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZIFERPWSCUSTOMERCREATE {


    /**
     * 
     * @param contactData
     * @param customerData
     * @return
     *     returns com.cnk.travelogix.custom.zif.erp.ws.custmastercreate.ZifErpTtStatusC
     */
    @WebMethod(operationName = "ZifTerpPartnerSave", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZIF_ERP_WS_CUSTOMER_CREATE:ZifTerpPartnerSaveRequest")
    @WebResult(name = "Status", targetNamespace = "")
    @RequestWrapper(localName = "ZifTerpPartnerSave", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.cnk.travelogix.custom.zif.erp.ws.custmastercreate.ZifTerpPartnerSave")
    @ResponseWrapper(localName = "ZifTerpPartnerSaveResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.cnk.travelogix.custom.zif.erp.ws.custmastercreate.ZifTerpPartnerSaveResponse")
    public ZifErpTtStatusC zifTerpPartnerSave(
        @WebParam(name = "ContactData", targetNamespace = "")
        ZifErpTtContmast contactData,
        @WebParam(name = "CustomerData", targetNamespace = "")
        ZifErpStCustmast customerData);

}
