
package com.cnk.travelogix.custom.so.createchange;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZIF_ERP_WS_SO_CREATE_CHANGE", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZIFERPWSSOCREATECHANGE {


    /**
     * 
     * @param soPartners
     * @param soItems
     * @param soConditions
     * @param soHeader
     * @return
     *     returns com.cnk.travelogix.custom.order.createupdate.ZttTerpSoStatus
     */
    @WebMethod(operationName = "ZifTerpSalesOrder")
    @WebResult(name = "Status", targetNamespace = "")
    @RequestWrapper(localName = "ZifTerpSalesOrder", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.cnk.travelogix.custom.order.createupdate.ZifTerpSalesOrder")
    @ResponseWrapper(localName = "ZifTerpSalesOrderResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.cnk.travelogix.custom.order.createupdate.ZifTerpSalesOrderResponse")
    public ZttTerpSoStatus zifTerpSalesOrder(
        @WebParam(name = "SoConditions", targetNamespace = "")
        ZttTerpSoConditions soConditions,
        @WebParam(name = "SoHeader", targetNamespace = "")
        ZifTerpSoHeader soHeader,
        @WebParam(name = "SoItems", targetNamespace = "")
        ZttTerpSoItemData soItems,
        @WebParam(name = "SoPartners", targetNamespace = "")
        ZttTerpSoPartners soPartners);

}
