
package com.cnk.travelogix.custom.zifwsb.invoice.create;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZIFWS_INVOICE_CREATE_N", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZIFWSINVOICECREATEN {


    /**
     * 
     * @param uniqid
     * @param iBillDoc
     * @return
     *     returns com.cnk.client.ZifstStatusDoc
     */
    @WebMethod(operationName = "ZIffmBillDocCreate", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZIFWS_INVOICE_CREATE_N:ZIffmBillDocCreateRequest")
    @WebResult(name = "Status", targetNamespace = "")
    @RequestWrapper(localName = "ZIffmBillDocCreate", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.cnk.client.ZIffmBillDocCreate")
    @ResponseWrapper(localName = "ZIffmBillDocCreateResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.cnk.client.ZIffmBillDocCreateResponse")
    public ZifstStatusDoc zIffmBillDocCreate(
        @WebParam(name = "IBillDoc", targetNamespace = "")
        ZttBilldoc iBillDoc,
        @WebParam(name = "Uniqid", targetNamespace = "")
        String uniqid);

}
