
package com.cnk.travelogix.custom.zifwsb.invoice.create;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ZIFWS_INVOICE_CREATE_N", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/C:/Users/i331944/Desktop/CNKIntegrations/zifwsb_invoice_create_n_1.wsdl")
public class ZIFWSINVOICECREATEN_Service extends Service
{

	private final static URL ZIFWSINVOICECREATEN_WSDL_LOCATION;
	private final static WebServiceException ZIFWSINVOICECREATEN_EXCEPTION;
	private final static QName ZIFWSINVOICECREATEN_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style",
			"ZIFWS_INVOICE_CREATE_N");

	static
	{
		URL url = null;
		WebServiceException e = null;
		try
		{
			url = new URL("file:/C:/Program%20Files/Java/jdk1.8.0_92/bin/zifwsb_invoice_create_n_1.wsdl");
		}
		catch (final MalformedURLException ex)
		{
			e = new WebServiceException(ex);
		}
		ZIFWSINVOICECREATEN_WSDL_LOCATION = url;
		ZIFWSINVOICECREATEN_EXCEPTION = e;
	}

	public ZIFWSINVOICECREATEN_Service()
	{
		super(__getWsdlLocation(), ZIFWSINVOICECREATEN_QNAME);
	}

	public ZIFWSINVOICECREATEN_Service(final WebServiceFeature... features)
	{
		super(__getWsdlLocation(), ZIFWSINVOICECREATEN_QNAME, features);
	}

	public ZIFWSINVOICECREATEN_Service(final URL wsdlLocation)
	{
		super(wsdlLocation, ZIFWSINVOICECREATEN_QNAME);
	}

	public ZIFWSINVOICECREATEN_Service(final URL wsdlLocation, final WebServiceFeature... features)
	{
		super(wsdlLocation, ZIFWSINVOICECREATEN_QNAME, features);
	}

	public ZIFWSINVOICECREATEN_Service(final URL wsdlLocation, final QName serviceName)
	{
		super(wsdlLocation, serviceName);
	}

	public ZIFWSINVOICECREATEN_Service(final URL wsdlLocation, final QName serviceName, final WebServiceFeature... features)
	{
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns ZIFWSINVOICECREATEN
	 */
	@WebEndpoint(name = "ZIFWSB_INVOICE_CREATE_N")
	public ZIFWSINVOICECREATEN getZIFWSBINVOICECREATEN()
	{
		return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZIFWSB_INVOICE_CREATE_N"),
				ZIFWSINVOICECREATEN.class);
	}

	/**
	 * 
	 * @param features
	 *           A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
	 *           the <code>features</code> parameter will have their default values.
	 * @return returns ZIFWSINVOICECREATEN
	 */
	@WebEndpoint(name = "ZIFWSB_INVOICE_CREATE_N")
	public ZIFWSINVOICECREATEN getZIFWSBINVOICECREATEN(final WebServiceFeature... features)
	{
		return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZIFWSB_INVOICE_CREATE_N"),
				ZIFWSINVOICECREATEN.class, features);
	}

	private static URL __getWsdlLocation()
	{
		if (ZIFWSINVOICECREATEN_EXCEPTION != null)
		{
			throw ZIFWSINVOICECREATEN_EXCEPTION;
		}
		return ZIFWSINVOICECREATEN_WSDL_LOCATION;
	}

}
