
package com.cnk.travelogix.custom.zif.erp.ws.complaints.feedback;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZIF_ERP_WS_COMPLAINTS_FEEDBACK", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZIFERPWSCOMPLAINTSFEEDBACK {


    /**
     * 
     * @param compPartners
     * @param compItem
     * @param compHeader
     * @return
     *     returns com.cnk.travelogix.custom.zif.erp.ws.complaints.feedback.ZttTerpComplaintsStatus
     */
    @WebMethod(operationName = "ZifTerpComplaints")
    @WebResult(name = "Status", targetNamespace = "")
    @RequestWrapper(localName = "ZifTerpComplaints", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.cnk.travelogix.custom.zif.erp.ws.complaints.feedback.ZifTerpComplaints")
    @ResponseWrapper(localName = "ZifTerpComplaintsResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.cnk.travelogix.custom.zif.erp.ws.complaints.feedback.ZifTerpComplaintsResponse")
    public ZttTerpComplaintsStatus zifTerpComplaints(
        @WebParam(name = "CompHeader", targetNamespace = "")
        ZifTerpComplaintsHeader compHeader,
        @WebParam(name = "CompItem", targetNamespace = "")
        ZttTerpComplaintsItems compItem,
        @WebParam(name = "CompPartners", targetNamespace = "")
        ZttTerpComplaintsPartners compPartners);

}
