
package com.cnk.travelogix.custom.zif.erp.ws.complaints.feedback;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZIF_ERP_WS_COMPLAINTS_FEEDBACK", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/C:/CNK-Documents/SAP-Backend-Integration/WSDL/CRM/UpdatedWSDL/hybriscrm_zif_erp_ws_complaints_feedback.wsdl")
public class ZIFERPWSCOMPLAINTSFEEDBACK_Service
    extends Service
{

    private final static URL ZIFERPWSCOMPLAINTSFEEDBACK_WSDL_LOCATION;
    private final static WebServiceException ZIFERPWSCOMPLAINTSFEEDBACK_EXCEPTION;
    private final static QName ZIFERPWSCOMPLAINTSFEEDBACK_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "ZIF_ERP_WS_COMPLAINTS_FEEDBACK");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/CNK-Documents/SAP-Backend-Integration/WSDL/CRM/UpdatedWSDL/hybriscrm_zif_erp_ws_complaints_feedback.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZIFERPWSCOMPLAINTSFEEDBACK_WSDL_LOCATION = url;
        ZIFERPWSCOMPLAINTSFEEDBACK_EXCEPTION = e;
    }

    public ZIFERPWSCOMPLAINTSFEEDBACK_Service() {
        super(__getWsdlLocation(), ZIFERPWSCOMPLAINTSFEEDBACK_QNAME);
    }

    public ZIFERPWSCOMPLAINTSFEEDBACK_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZIFERPWSCOMPLAINTSFEEDBACK_QNAME, features);
    }

    public ZIFERPWSCOMPLAINTSFEEDBACK_Service(URL wsdlLocation) {
        super(wsdlLocation, ZIFERPWSCOMPLAINTSFEEDBACK_QNAME);
    }

    public ZIFERPWSCOMPLAINTSFEEDBACK_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZIFERPWSCOMPLAINTSFEEDBACK_QNAME, features);
    }

    public ZIFERPWSCOMPLAINTSFEEDBACK_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZIFERPWSCOMPLAINTSFEEDBACK_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZIFERPWSCOMPLAINTSFEEDBACK
     */
    @WebEndpoint(name = "ZIF_ERP_WS_COMPLAINTS_FEEDBACK")
    public ZIFERPWSCOMPLAINTSFEEDBACK getZIFERPWSCOMPLAINTSFEEDBACK() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZIF_ERP_WS_COMPLAINTS_FEEDBACK"), ZIFERPWSCOMPLAINTSFEEDBACK.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZIFERPWSCOMPLAINTSFEEDBACK
     */
    @WebEndpoint(name = "ZIF_ERP_WS_COMPLAINTS_FEEDBACK")
    public ZIFERPWSCOMPLAINTSFEEDBACK getZIFERPWSCOMPLAINTSFEEDBACK(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZIF_ERP_WS_COMPLAINTS_FEEDBACK"), ZIFERPWSCOMPLAINTSFEEDBACK.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZIFERPWSCOMPLAINTSFEEDBACK_EXCEPTION!= null) {
            throw ZIFERPWSCOMPLAINTSFEEDBACK_EXCEPTION;
        }
        return ZIFERPWSCOMPLAINTSFEEDBACK_WSDL_LOCATION;
    }

}
