

package suppliermasterscore;

import java.util.*;
import java.io.Serializable;
import de.hybris.platform.util.*;
import de.hybris.platform.core.*;
import de.hybris.platform.jalo.JaloBusinessException;
import de.hybris.platform.jalo.type.*;
import de.hybris.platform.persistence.type.*;
import de.hybris.platform.persistence.enumeration.*;
import de.hybris.platform.persistence.property.PersistenceManager;
import de.hybris.platform.persistence.*;

/**
 * Generated by hybris Platform.
 */
@SuppressWarnings({"cast","unused","boxing","null", "PMD"})
public class GeneratedTypeInitializer extends AbstractTypeInitializer
{
	/**
	 * Generated by hybris Platform.
	 */
	public GeneratedTypeInitializer( ManagerEJB manager, Map params )
	{
		super( manager, params );
	}


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected void performRemoveObjects( ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// no-op by now
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateTypes
	
	
		createItemType(
			"SupplierEmergencyContact",
			"ContactDetails",
			com.cnk.travelogix.supplier.core.contact.jalo.SupplierEmergencyContact.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"AbstractDynamicPolicy",
			"GenericItem",
			com.cnk.travelogix.supplier.masterdata.core.policy.AbstractDynamicPolicy.class,
			"de.hybris.platform.persistence.suppliermasterscore_AbstractDynamicPolicy",
			false,
			null,
			true
		);
	
		createItemType(
			"AccoDynamicPolicy",
			"AbstractDynamicPolicy",
			com.cnk.travelogix.supplier.masterdata.core.policy.AccoDynamicPolicy.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"ActivityDynamicPolicy",
			"AbstractDynamicPolicy",
			com.cnk.travelogix.supplier.masterdata.core.policy.ActivityDynamicPolicy.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"CruiseDynamicPolicy",
			"AbstractDynamicPolicy",
			com.cnk.travelogix.supplier.masterdata.core.policy.CruiseDynamicPolicy.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"FlightsDynamicPolicy",
			"AbstractDynamicPolicy",
			com.cnk.travelogix.supplier.masterdata.core.policy.FlightsDynamicPolicy.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"HolidaysDynamicPolicy",
			"AbstractDynamicPolicy",
			com.cnk.travelogix.supplier.masterdata.core.policy.HolidaysDynamicPolicy.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"TransportationDynamicPolicy",
			"AbstractDynamicPolicy",
			com.cnk.travelogix.supplier.masterdata.core.policy.TransportationDynamicPolicy.class,
			null,
			false,
			null,
			false
		);
	
		createRelationType(
			"EmergencyContact2Country",
			"de.hybris.platform.persistence.link.suppliermasterscore_EmergencyContact2Country",
			false
		);
	
		createRelationType(
			"EmergencyContact2Continent",
			"de.hybris.platform.persistence.link.suppliermasterscore_EmergencyContact2Continent",
			false
		);
	
		createRelationType(
			"EmergencyContact2Region",
			"de.hybris.platform.persistence.link.suppliermasterscore_EmergencyContact2Region",
			false
		);
	
		createRelationType(
			"EmergencyContact2City",
			"de.hybris.platform.persistence.link.suppliermasterscore_EmergencyContact2City",
			false
		);
	
		createRelationType(
			"Policy2DynamicPolicy",
			null,
			true
		);
	
		createEnumerationType(
			"SupplierType",
			null
		);
	
		createEnumerationType(
			"SupplierEnablerCategory",
			null
		);
	
		createEnumerationType(
			"SuppliersLOB",
			null
		);
	
		createEnumerationType(
			"Segment",
			null
		);
	
		createEnumerationType(
			"CommercialSlabType",
			null
		);
	
		createEnumerationType(
			"CalculationType",
			null
		);
	
		createEnumerationType(
			"FOCType",
			null
		);
	
		createEnumerationType(
			"RunningType",
			null
		);
	
		createEnumerationType(
			"SupDefValidityContext",
			null
		);
	
		createEnumerationType(
			"AncillaryCategory",
			null
		);
	
		createEnumerationType(
			"TransferType",
			null
		);
	
		createEnumerationType(
			"CityTierType",
			null
		);
	
		createEnumerationType(
			"SeasonType",
			null
		);
	
		createEnumerationType(
			"TaxType",
			null
		);
	
		createEnumerationType(
			"NonAirPriceComponentType",
			null
		);
	
		createEnumerationType(
			"SippCode",
			null
		);
	
		createEnumerationType(
			"TransportCategory",
			null
		);
	
		createEnumerationType(
			"JourneyType",
			null
		);
	
		createEnumerationType(
			"AncillaryType",
			null
		);
	
		createEnumerationType(
			"RatesDefinedForType",
			null
		);
	
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performModifyTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performModifyTypes
	

	
	
				single_createattr_SupplierEmergencyContact_contactPerson();
			
				single_createattr_SupplierEmergencyContact_displayInTravelDocuments();
			
				single_createattr_SupplierEmergencyContact_productCategory();
			
				single_createattr_AbstractDynamicPolicy_definedBy();
			
				single_createattr_AbstractDynamicPolicy_fromDaysHour();
			
				single_createattr_AbstractDynamicPolicy_toDaysHour();
			
				single_createattr_AbstractDynamicPolicy_chargesInPercentage();
			
				single_createattr_AbstractDynamicPolicy_currency();
			
				single_createattr_AbstractDynamicPolicy_chargesAmount();
			
				single_createattr_AccoDynamicPolicy_chargeNight();
			
				single_createattr_AccoDynamicPolicy_perRoom();
			
				single_createattr_AccoDynamicPolicy_perPerson();
			
				single_createattr_ActivityDynamicPolicy_perPerson();
			
				single_createattr_ActivityDynamicPolicy_perAdult();
			
				single_createattr_ActivityDynamicPolicy_perChild();
			
				single_createattr_ActivityDynamicPolicy_perInfant();
			
				single_createattr_ActivityDynamicPolicy_allPaxTypes();
			
				single_createattr_CruiseDynamicPolicy_perPassenger();
			
				single_createattr_CruiseDynamicPolicy_perCabin();
			
				single_createattr_FlightsDynamicPolicy_fareTypes();
			
				single_createattr_FlightsDynamicPolicy_perAdult();
			
				single_createattr_FlightsDynamicPolicy_perChild();
			
				single_createattr_FlightsDynamicPolicy_perInfant();
			
				single_createattr_HolidaysDynamicPolicy_perRoom();
			
				single_createattr_HolidaysDynamicPolicy_allPaxTypes();
			
				single_createattr_HolidaysDynamicPolicy_adultInTwin();
			
				single_createattr_HolidaysDynamicPolicy_adultInDouble();
			
				single_createattr_HolidaysDynamicPolicy_childWithExtraBed();
			
				single_createattr_HolidaysDynamicPolicy_childWithNoBed();
			
				single_createattr_TransportationDynamicPolicy_perAdult();
			
				single_createattr_TransportationDynamicPolicy_perChild();
			
				single_createattr_TransportationDynamicPolicy_perPerson();
			
				single_createattr_TransportationDynamicPolicy_perVehicle();
			
		createRelationAttributes(
			"EmergencyContact2Country", 
			false, 

			"supplierEmergencycontacts", 
			"SupplierEmergencyContact", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.SET,
			"countries", 
			"Country", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.SET
		);
	
		createRelationAttributes(
			"EmergencyContact2Continent", 
			false, 

			"supplierEmergencycontacts", 
			"SupplierEmergencyContact", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.SET,
			"continents", 
			"Continent", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.SET
		);
	
		createRelationAttributes(
			"EmergencyContact2Region", 
			false, 

			"supplierEmergencycontacts", 
			"SupplierEmergencyContact", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.SET,
			"regions", 
			"Region", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.SET
		);
	
		createRelationAttributes(
			"EmergencyContact2City", 
			false, 

			"supplierEmergencycontacts", 
			"SupplierEmergencyContact", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.SET,
			"cities", 
			"City", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.SET
		);
	
		createRelationAttributes(
			"Policy2DynamicPolicy", 
			false, 

			"policy", 
			"TravelogixPolicy", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"canOrAmndPolicies", 
			"AbstractDynamicPolicy", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.PARTOF_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	

	}

	
	public void single_createattr_SupplierEmergencyContact_contactPerson() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"SupplierEmergencyContact", 
					"contactPerson",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_SupplierEmergencyContact_displayInTravelDocuments() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"SupplierEmergencyContact", 
					"displayInTravelDocuments",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_SupplierEmergencyContact_productCategory() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"SupplierEmergencyContact", 
					"productCategory",  
					null,
					"ProductCategory",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractDynamicPolicy_definedBy() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractDynamicPolicy", 
					"definedBy",  
					null,
					"PolicyDefinedByType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractDynamicPolicy_fromDaysHour() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractDynamicPolicy", 
					"fromDaysHour",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractDynamicPolicy_toDaysHour() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractDynamicPolicy", 
					"toDaysHour",  
					null,
					"java.lang.Integer",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractDynamicPolicy_chargesInPercentage() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractDynamicPolicy", 
					"chargesInPercentage",  
					null,
					"java.lang.Double",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractDynamicPolicy_currency() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractDynamicPolicy", 
					"currency",  
					null,
					"Currency",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AbstractDynamicPolicy_chargesAmount() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AbstractDynamicPolicy", 
					"chargesAmount",  
					null,
					"java.lang.Double",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoDynamicPolicy_chargeNight() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoDynamicPolicy", 
					"chargeNight",  
					null,
					"java.lang.Double",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoDynamicPolicy_perRoom() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoDynamicPolicy", 
					"perRoom",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_AccoDynamicPolicy_perPerson() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"AccoDynamicPolicy", 
					"perPerson",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_ActivityDynamicPolicy_perPerson() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"ActivityDynamicPolicy", 
					"perPerson",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_ActivityDynamicPolicy_perAdult() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"ActivityDynamicPolicy", 
					"perAdult",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_ActivityDynamicPolicy_perChild() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"ActivityDynamicPolicy", 
					"perChild",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_ActivityDynamicPolicy_perInfant() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"ActivityDynamicPolicy", 
					"perInfant",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_ActivityDynamicPolicy_allPaxTypes() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"ActivityDynamicPolicy", 
					"allPaxTypes",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CruiseDynamicPolicy_perPassenger() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CruiseDynamicPolicy", 
					"perPassenger",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CruiseDynamicPolicy_perCabin() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CruiseDynamicPolicy", 
					"perCabin",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_FlightsDynamicPolicy_fareTypes() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"FlightsDynamicPolicy", 
					"fareTypes",  
					null,
					"localized:java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_FlightsDynamicPolicy_perAdult() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"FlightsDynamicPolicy", 
					"perAdult",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_FlightsDynamicPolicy_perChild() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"FlightsDynamicPolicy", 
					"perChild",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_FlightsDynamicPolicy_perInfant() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"FlightsDynamicPolicy", 
					"perInfant",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidaysDynamicPolicy_perRoom() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidaysDynamicPolicy", 
					"perRoom",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidaysDynamicPolicy_allPaxTypes() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidaysDynamicPolicy", 
					"allPaxTypes",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidaysDynamicPolicy_adultInTwin() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidaysDynamicPolicy", 
					"adultInTwin",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidaysDynamicPolicy_adultInDouble() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidaysDynamicPolicy", 
					"adultInDouble",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidaysDynamicPolicy_childWithExtraBed() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidaysDynamicPolicy", 
					"childWithExtraBed",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HolidaysDynamicPolicy_childWithNoBed() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HolidaysDynamicPolicy", 
					"childWithNoBed",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_TransportationDynamicPolicy_perAdult() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"TransportationDynamicPolicy", 
					"perAdult",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_TransportationDynamicPolicy_perChild() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"TransportationDynamicPolicy", 
					"perChild",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_TransportationDynamicPolicy_perPerson() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"TransportationDynamicPolicy", 
					"perPerson",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_TransportationDynamicPolicy_perVehicle() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"TransportationDynamicPolicy", 
					"perVehicle",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateObjects( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateObjects
	
	
		createEnumerationValues(
			"SupplierType",
			false,
			Arrays.asList( new String[] {
			
				"ENABLER",
				"SOURCE",
				"BOTH"
			} )
		);
	
		createEnumerationValues(
			"SupplierEnablerCategory",
			true,
			Arrays.asList( new String[] {
			
				"GDS",
				"DIRECT_CONNECT",
				"PAYMENT_GATEWAY",
				"SWITCH",
				"SMS_GATEWAY",
				"CONTENT_PROVIDER",
				"TRAVEL_ACCESSORIES",
				"LOGISTIC",
				"SETTLEMENT"
			} )
		);
	
		createEnumerationValues(
			"SuppliersLOB",
			true,
			Arrays.asList( new String[] {
			
				"GROUPS",
				"FIT",
				"MICE",
				"INCENTIVES"
			} )
		);
	
		createEnumerationValues(
			"Segment",
			false,
			Arrays.asList( new String[] {
			
				"ACTIVE",
				"PASSIVE",
				"BOTH",
				"OTHER_GDS"
			} )
		);
	
		createEnumerationValues(
			"CommercialSlabType",
			true,
			Arrays.asList( new String[] {
			
				"TOTAL_REVENUE",
				"NO_OF_TICKETS",
				"NO_OF_ROOMS",
				"NO_OF_PASSENGERS",
				"NO_OF_SECTORS",
				"NO_OF_NIGHTS",
				"NO_OF_BOOKINGS",
				"NO_OF_SEATS",
				"NO_OF_SEGMENTS",
				"NO_OF_ADULTS",
				"NO_OF_CHILDREN"
			} )
		);
	
		createEnumerationValues(
			"CalculationType",
			false,
			Arrays.asList( new String[] {
			
				"NETT_OFF"
			} )
		);
	
		createEnumerationValues(
			"FOCType",
			false,
			Arrays.asList( new String[] {
			
				"FOC",
				"UPGRADE"
			} )
		);
	
		createEnumerationValues(
			"RunningType",
			false,
			Arrays.asList( new String[] {
			
				"TICKETS",
				"ROOMS",
				"PASSENGERS"
			} )
		);
	
		createEnumerationValues(
			"SupDefValidityContext",
			false,
			Arrays.asList( new String[] {
			
				"TRAVEL",
				"TICKETING",
				"TRAVEL_AND_TICKETING",
				"SALE",
				"TRAVEL_AND_SALE"
			} )
		);
	
		createEnumerationValues(
			"AncillaryCategory",
			true,
			Arrays.asList( new String[] {
			
				"SERVICE",
				"RENTAL"
			} )
		);
	
		createEnumerationValues(
			"TransferType",
			true,
			Arrays.asList( new String[] {
			
				"PRIVATE",
				"SHARED",
				"SEAT_IN_COACH"
			} )
		);
	
		createEnumerationValues(
			"CityTierType",
			true,
			Arrays.asList( new String[] {
			
				"TIER_1",
				"TIER_2",
				"TIER_3"
			} )
		);
	
		createEnumerationValues(
			"SeasonType",
			false,
			Arrays.asList( new String[] {
			
				"LOW_SEASON",
				"MID_SEASON",
				"HIGH_SEASON",
				"PEAK_SEASON"
			} )
		);
	
		createEnumerationValues(
			"TaxType",
			true,
			Arrays.asList( new String[] {
			
				"LUXURY_TAX",
				"VAT",
				"SERVICE_TAX"
			} )
		);
	
		createEnumerationValues(
			"NonAirPriceComponentType",
			true,
			Arrays.asList( new String[] {
			
				"BASE_FARE",
				"YQ_TAX",
				"FUEL_SURCHARGE",
				"USER_DEVELOPMENT_FEE",
				"PASSENGER_SERVICE_FEE",
				"OTHER_CHARGES",
				"TRANSACTION_FEE",
				"TOTAL",
				"ROOM_RATE",
				"LUXURY_TAX",
				"VAT_TAX",
				"ANCILLARY_RATE"
			} )
		);
	
		createEnumerationValues(
			"SippCode",
			true,
			Arrays.asList( new String[] {
			
				"CDMR",
				"MDMR",
				"DNMR"
			} )
		);
	
		createEnumerationValues(
			"TransportCategory",
			true,
			Arrays.asList( new String[] {
			
				"TRANSFER",
				"RENTAL",
				"CAR_PACKAGE"
			} )
		);
	
		createEnumerationValues(
			"JourneyType",
			false,
			Arrays.asList( new String[] {
			
				"ONE_WAY",
				"RETURN",
				"MULTI_CITY"
			} )
		);
	
		createEnumerationValues(
			"AncillaryType",
			false,
			Arrays.asList( new String[] {
			
				"ENTERTAINMENT",
				"PARKING",
				"INTERNET",
				"RESTAURANT",
				"TRAILER_ACCESSORIES",
				"PURCHASE_ITEM",
				"CAMPING_ITEM",
				"INSURANCE",
				"PETS",
				"SPA",
				"TRANSFER",
				"CYCLING_PACKAGE"
			} )
		);
	
		createEnumerationValues(
			"RatesDefinedForType",
			true,
			Arrays.asList( new String[] {
			
				"PER_NIGHT",
				"DAY_USE",
				"HOURLY",
				"CITY_TRANSFERRED",
				"INTER_CITY_TRANSFER",
				"CITY_USE",
				"OUTSTATION"
			} )
		);
	
		single_setRelAttributeProperties_EmergencyContact2Country_source();
	
		single_setRelAttributeProperties_EmergencyContact2Continent_source();
	
		single_setRelAttributeProperties_EmergencyContact2Region_source();
	
		single_setRelAttributeProperties_EmergencyContact2City_source();
	
		single_setRelAttributeProperties_Policy2DynamicPolicy_source();
	
		single_setRelAttributeProperties_EmergencyContact2Country_target();
	
		single_setRelAttributeProperties_EmergencyContact2Continent_target();
	
		single_setRelAttributeProperties_EmergencyContact2Region_target();
	
		single_setRelAttributeProperties_EmergencyContact2City_target();
	
		single_setRelAttributeProperties_Policy2DynamicPolicy_target();
	
		connectRelation(
			"EmergencyContact2Country", 
			false, 
			"supplierEmergencycontacts", 
			"SupplierEmergencyContact", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"countries", 
			"Country", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"EmergencyContact2Continent", 
			false, 
			"supplierEmergencycontacts", 
			"SupplierEmergencyContact", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"continents", 
			"Continent", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"EmergencyContact2Region", 
			false, 
			"supplierEmergencycontacts", 
			"SupplierEmergencyContact", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"regions", 
			"Region", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"EmergencyContact2City", 
			false, 
			"supplierEmergencycontacts", 
			"SupplierEmergencyContact", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"cities", 
			"City", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"Policy2DynamicPolicy", 
			false, 
			"policy", 
			"TravelogixPolicy", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"canOrAmndPolicies", 
			"AbstractDynamicPolicy", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.PARTOF_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"SupplierEmergencyContact",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_SupplierEmergencyContact_contactPerson();
		
			single_setAttributeProperties_SupplierEmergencyContact_displayInTravelDocuments();
		
			single_setAttributeProperties_SupplierEmergencyContact_productCategory();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"AbstractDynamicPolicy",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_AbstractDynamicPolicy_definedBy();
		
			single_setAttributeProperties_AbstractDynamicPolicy_fromDaysHour();
		
			single_setAttributeProperties_AbstractDynamicPolicy_toDaysHour();
		
			single_setAttributeProperties_AbstractDynamicPolicy_chargesInPercentage();
		
			single_setAttributeProperties_AbstractDynamicPolicy_currency();
		
			single_setAttributeProperties_AbstractDynamicPolicy_chargesAmount();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"AccoDynamicPolicy",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_AccoDynamicPolicy_chargeNight();
		
			single_setAttributeProperties_AccoDynamicPolicy_perRoom();
		
			single_setAttributeProperties_AccoDynamicPolicy_perPerson();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"ActivityDynamicPolicy",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_ActivityDynamicPolicy_perPerson();
		
			single_setAttributeProperties_ActivityDynamicPolicy_perAdult();
		
			single_setAttributeProperties_ActivityDynamicPolicy_perChild();
		
			single_setAttributeProperties_ActivityDynamicPolicy_perInfant();
		
			single_setAttributeProperties_ActivityDynamicPolicy_allPaxTypes();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"CruiseDynamicPolicy",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_CruiseDynamicPolicy_perPassenger();
		
			single_setAttributeProperties_CruiseDynamicPolicy_perCabin();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"FlightsDynamicPolicy",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_FlightsDynamicPolicy_fareTypes();
		
			single_setAttributeProperties_FlightsDynamicPolicy_perAdult();
		
			single_setAttributeProperties_FlightsDynamicPolicy_perChild();
		
			single_setAttributeProperties_FlightsDynamicPolicy_perInfant();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HolidaysDynamicPolicy",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_HolidaysDynamicPolicy_perRoom();
		
			single_setAttributeProperties_HolidaysDynamicPolicy_allPaxTypes();
		
			single_setAttributeProperties_HolidaysDynamicPolicy_adultInTwin();
		
			single_setAttributeProperties_HolidaysDynamicPolicy_adultInDouble();
		
			single_setAttributeProperties_HolidaysDynamicPolicy_childWithExtraBed();
		
			single_setAttributeProperties_HolidaysDynamicPolicy_childWithNoBed();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"TransportationDynamicPolicy",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_TransportationDynamicPolicy_perAdult();
		
			single_setAttributeProperties_TransportationDynamicPolicy_perChild();
		
			single_setAttributeProperties_TransportationDynamicPolicy_perPerson();
		
			single_setAttributeProperties_TransportationDynamicPolicy_perVehicle();
		
				setDefaultProperties(
					"SupplierType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"SupplierEnablerCategory",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"SuppliersLOB",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"Segment",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"CommercialSlabType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"CalculationType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"FOCType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"RunningType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"SupDefValidityContext",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"AncillaryCategory",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"TransferType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"CityTierType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"SeasonType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"TaxType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"NonAirPriceComponentType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"SippCode",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"TransportCategory",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"JourneyType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"AncillaryType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"RatesDefinedForType",
					true,
					true,
					null
				);
			
	}


		
						public void single_setAttributeProperties_SupplierEmergencyContact_contactPerson() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"SupplierEmergencyContact", 
								"contactPerson",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_SupplierEmergencyContact_displayInTravelDocuments() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"SupplierEmergencyContact", 
								"displayInTravelDocuments",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_SupplierEmergencyContact_productCategory() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"SupplierEmergencyContact", 
								"productCategory",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractDynamicPolicy_definedBy() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractDynamicPolicy", 
								"definedBy",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractDynamicPolicy_fromDaysHour() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractDynamicPolicy", 
								"fromDaysHour",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractDynamicPolicy_toDaysHour() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractDynamicPolicy", 
								"toDaysHour",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractDynamicPolicy_chargesInPercentage() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractDynamicPolicy", 
								"chargesInPercentage",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractDynamicPolicy_currency() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractDynamicPolicy", 
								"currency",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AbstractDynamicPolicy_chargesAmount() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AbstractDynamicPolicy", 
								"chargesAmount",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoDynamicPolicy_chargeNight() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoDynamicPolicy", 
								"chargeNight",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoDynamicPolicy_perRoom() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoDynamicPolicy", 
								"perRoom",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_AccoDynamicPolicy_perPerson() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"AccoDynamicPolicy", 
								"perPerson",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_ActivityDynamicPolicy_perPerson() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"ActivityDynamicPolicy", 
								"perPerson",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_ActivityDynamicPolicy_perAdult() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"ActivityDynamicPolicy", 
								"perAdult",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_ActivityDynamicPolicy_perChild() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"ActivityDynamicPolicy", 
								"perChild",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_ActivityDynamicPolicy_perInfant() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"ActivityDynamicPolicy", 
								"perInfant",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_ActivityDynamicPolicy_allPaxTypes() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"ActivityDynamicPolicy", 
								"allPaxTypes",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CruiseDynamicPolicy_perPassenger() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CruiseDynamicPolicy", 
								"perPassenger",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CruiseDynamicPolicy_perCabin() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CruiseDynamicPolicy", 
								"perCabin",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_FlightsDynamicPolicy_fareTypes() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"FlightsDynamicPolicy", 
								"fareTypes",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_FlightsDynamicPolicy_perAdult() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"FlightsDynamicPolicy", 
								"perAdult",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_FlightsDynamicPolicy_perChild() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"FlightsDynamicPolicy", 
								"perChild",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_FlightsDynamicPolicy_perInfant() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"FlightsDynamicPolicy", 
								"perInfant",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidaysDynamicPolicy_perRoom() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidaysDynamicPolicy", 
								"perRoom",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidaysDynamicPolicy_allPaxTypes() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidaysDynamicPolicy", 
								"allPaxTypes",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidaysDynamicPolicy_adultInTwin() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidaysDynamicPolicy", 
								"adultInTwin",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidaysDynamicPolicy_adultInDouble() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidaysDynamicPolicy", 
								"adultInDouble",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidaysDynamicPolicy_childWithExtraBed() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidaysDynamicPolicy", 
								"childWithExtraBed",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HolidaysDynamicPolicy_childWithNoBed() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HolidaysDynamicPolicy", 
								"childWithNoBed",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_TransportationDynamicPolicy_perAdult() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"TransportationDynamicPolicy", 
								"perAdult",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_TransportationDynamicPolicy_perChild() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"TransportationDynamicPolicy", 
								"perChild",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_TransportationDynamicPolicy_perPerson() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"TransportationDynamicPolicy", 
								"perPerson",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_TransportationDynamicPolicy_perVehicle() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"TransportationDynamicPolicy", 
								"perVehicle",
								false, 
								Boolean.FALSE,
								"Boolean.FALSE",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
								public void single_setRelAttributeProperties_EmergencyContact2Country_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"Country", 
										"supplierEmergencycontacts",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_EmergencyContact2Country_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"SupplierEmergencyContact", 
										"countries",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_EmergencyContact2Continent_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"Continent", 
										"supplierEmergencycontacts",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_EmergencyContact2Continent_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"SupplierEmergencyContact", 
										"continents",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_EmergencyContact2Region_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"Region", 
										"supplierEmergencycontacts",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_EmergencyContact2Region_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"SupplierEmergencyContact", 
										"regions",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_EmergencyContact2City_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"City", 
										"supplierEmergencycontacts",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_EmergencyContact2City_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"SupplierEmergencyContact", 
										"cities",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_Policy2DynamicPolicy_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"AbstractDynamicPolicy", 
										"policy",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_Policy2DynamicPolicy_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"TravelogixPolicy", 
										"canOrAmndPolicies",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
}

	