
package com.cnk.travelogix.custom.zif.erp.ws.opportunity;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZIF_ERP_WS_OPPORTUNITY", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/C:/CNK-Documents/SAP-Backend-Integration/WSDL/CRM/hybriscrm_zif_erp_ws_opportunity.wsdl")
public class ZIFERPWSOPPORTUNITY_Service
    extends Service
{

    private final static URL ZIFERPWSOPPORTUNITY_WSDL_LOCATION;
    private final static WebServiceException ZIFERPWSOPPORTUNITY_EXCEPTION;
    private final static QName ZIFERPWSOPPORTUNITY_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "ZIF_ERP_WS_OPPORTUNITY");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/CNK-Documents/SAP-Backend-Integration/WSDL/CRM/hybriscrm_zif_erp_ws_opportunity.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZIFERPWSOPPORTUNITY_WSDL_LOCATION = url;
        ZIFERPWSOPPORTUNITY_EXCEPTION = e;
    }

    public ZIFERPWSOPPORTUNITY_Service() {
        super(__getWsdlLocation(), ZIFERPWSOPPORTUNITY_QNAME);
    }

    public ZIFERPWSOPPORTUNITY_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZIFERPWSOPPORTUNITY_QNAME, features);
    }

    public ZIFERPWSOPPORTUNITY_Service(URL wsdlLocation) {
        super(wsdlLocation, ZIFERPWSOPPORTUNITY_QNAME);
    }

    public ZIFERPWSOPPORTUNITY_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZIFERPWSOPPORTUNITY_QNAME, features);
    }

    public ZIFERPWSOPPORTUNITY_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZIFERPWSOPPORTUNITY_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZIFERPWSOPPORTUNITY
     */
    @WebEndpoint(name = "ZIF_ERP_WS_OPPORTUNITY")
    public ZIFERPWSOPPORTUNITY getZIFERPWSOPPORTUNITY() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZIF_ERP_WS_OPPORTUNITY"), ZIFERPWSOPPORTUNITY.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZIFERPWSOPPORTUNITY
     */
    @WebEndpoint(name = "ZIF_ERP_WS_OPPORTUNITY")
    public ZIFERPWSOPPORTUNITY getZIFERPWSOPPORTUNITY(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZIF_ERP_WS_OPPORTUNITY"), ZIFERPWSOPPORTUNITY.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZIFERPWSOPPORTUNITY_EXCEPTION!= null) {
            throw ZIFERPWSOPPORTUNITY_EXCEPTION;
        }
        return ZIFERPWSOPPORTUNITY_WSDL_LOCATION;
    }

}
